amp-labs/react

- src/components/Configure/ObjectManagementNav/index.tsx
> [ENG-551] style: hide write section

- src/components/Configure/ConfigureInstallationBase.tsx
- src/components/Configure/CreateInstallation.tsx
- src/components/Configure/InstallIntegration.tsx
- src/components/Configure/ObjectManagementNav/index.tsx
- src/components/Configure/UpdateInstallation.tsx
- src/components/Configure/fields/FieldMappings/FieldMapping.tsx
- src/components/Configure/fields/FieldMappings/RequiredFieldMappings.tsx
- src/components/Configure/fields/FieldMappings/setFieldMapping.ts
- src/components/Configure/fields/OptionalFields/OptionalFields.tsx
- src/components/Configure/fields/OptionalFields/setOptionalField.ts
- src/components/Configure/fields/RequiredFields.tsx
- src/components/Configure/fields/WriteFields/WriteFields.tsx
- src/components/Configure/state/ConfigurationStateProvider.tsx
- src/components/Configure/state/utils.ts
- src/components/Configure/types.ts
- src/components/Configure/utils.ts
- separates read state into own field
- preps for write state field
app should work as expected
2. **refactor read state**
3. add write state
4. connect data to write state slice
5. submit write state slice
> [ENG-512]refactor: read state

- src/components/Configure/ObjectManagementNav/OtherTab.tsx
- src/components/Configure/ObjectManagementNav/index.tsx
- src/components/Configure/content/fields/WriteFields/setNonConfigurableWriteField.tsx
- src/components/Configure/state/utils.ts
- src/components/Configure/types.ts
- src/components/Configure/utils.ts
adds pending state to other / write tab
2. ~refactor read state~
3. ~add write state to context~
4. ~connect data to write state slice~ 
4a. ~connect hydratedRevision data~
4b. connect config data
5. submit write state slice
6. **add isModified / in progress state**
> feat: add pending state to write tab

- .eslintrc.cjs
- src/assets/TrashIcon.tsx
- src/components/Configure/content/UninstallContent.tsx
- src/components/Configure/state/HydratedRevisionContext.tsx
- src/components/Connect/ConnectedSuccessBox.tsx
- src/components/Connect/OAuthPopup.tsx
- src/components/ErrorTextBox.tsx
- src/context/InstallIntegrationContext.tsx
adds max-len to match console code style choice.
> build: add max-len to eslint config

- src/hooks/useIsIntegrationInstalled.ts
looks like our CI didn't catch this build failure. undoing type change for time being.
> fix: undo type change to unblock build

- package.json
Incrementing minor version since this release includes a new feature: write actions
> build: release v1.2.0

- src/components/Configure/content/useMutateInstallation.tsx
- src/components/Configure/content/useSelectedConfigureState.tsx
- src/components/Configure/nav/ObjectManagementNav/index.tsx
- src/components/Configure/state/ConfigurationStateProvider.tsx
- src/components/Configure/state/utils.ts
Reverts amp-labs/react#286
change breaks configureState.
> Revert "fix: infinite loop if empty configuration state"

- src/components/Oauth/NoSubdomainEntry/LandingContent.tsx
- src/components/Oauth/OauthCardLayout.tsx
- src/components/Oauth/Salesforce/SubdomainEntry.tsx
- src/components/Oauth/WorkspaceEntry/WorkspaceEntry.tsx
Card styles have been copied and we don't want to update these styles in multiple places. Consolidates to use a common layout component. No UI changes.
> [ENG-936] refactor: OauthCardLayout

- src/components/Oauth/NoWorkspaceEntry/NoWorkspaceOauthFlow.tsx
- src/components/Oauth/OAuthPopup.tsx
- src/components/Oauth/WorkspaceEntry/WorkspaceOauthFlow.tsx
- src/constants.ts
clean up for using generic providers
- removes use of subdomain if workspace is preferred
- removes constants file for providers
> [ENG-810] cleanup: removes unused constants file

- src/components/Oauth/OAuthPopup.tsx
Redundant behavior as backend does this close.
> chore: remove window.close() from OAuthPopup.tsx

- src/components/Oauth/OauthFlow/OauthFlow.tsx
- src/components/Oauth/WorkspaceEntry/WorkspaceOauthFlow.tsx
PR for switching Salesforce to use custom flow and generalized WorkspaceEntry Oauth flow for other workspace providers.
> [ENG-933] launch: remove feature flag for WorkspaceEntry oauth flow

- package.json
Incrementing version to 1.4.0, which includes:
- `X-Amp-Client` headers being included in each API request
- support for providers that require a workspace entry
> release: Update version to v1.4.0

- package.json
New release for:
- fix for optional consumerName and groupName parameters
- fix for unexpected error message colors
> Release: Update package.json to v1.4.1

- package.json
includes bug fix https://github.com/amp-labs/react/pull/349
> release: update version to 1.4.2

- package.json
Adding "select all" functionality for write objects
> release: Update version to 1.4.3

- src/components/Configure/layout/ConditionalProxyLayout/ConditionalProxyLayout.tsx
- src/services/version.ts
Add !isLoading condition in if check to call createInstallation to prevent multiple calls being made.
> [bugfix] add isLoading to condintion

- .gitignore
- package.json
Fix issue where proxy-only integrations sometimes created more than one installations.
> release: update version to v1.4.4

- package.json
Migrating from `read.standardObjects` to `read.objects`
> release: update version to 1.5.0

- package.json
- better oauth flow error handling
> build: update version to v1.5.1

- src/components/Configure/content/fields/OptionalFields/OptionalFields.tsx
adds select all functionality to read optional field
> [ENG-1195] feat: add select all to read optional fields 

- src/components/Configure/content/fields/RequiredFields.tsx
- src/components/Oauth/fetchOAuthPopupURL.ts
- updates connected app to provider app text
- add gap to required field tag
> [ENG-1193, ENG-1191] polish: update text to provider app

- package.json
Fix oauth2opts backwards incompatibility
> Update package.json to v1.5.3

- package.json
- Support for alternative auth types (basic auth, API key based auth, oauth2 client credentials)
> release: update version to v1.6.0

- src/components/Oauth/WorkspaceEntry/ClientCredentialsContent.tsx
disabled state is inverted. 
@eberle1080 - if you have this integration set up, can you run test this? 
[Loom Video Marketo](https://www.loom.com/share/41969adeca244c6d83c05f00cd6bb3a1)
> [ENG-1401] fix: disabled state of client credentials form

- src/components/BasicAuth/BasicAuthFlow/LandingContent.tsx
- src/components/Oauth/NoWorkspaceEntry/NoWorkspaceOauthClientCredsFlow.tsx
- src/components/Oauth/WorkspaceEntry/WorkspaceOauthClientCredsFlow.tsx
Some passwords are optional in basic auth. Adds loading icon.
> [ENG-1403, ENG-1421] feat: make basic auth flow password optional, adding loading icon

- package.json
- Add support for `project` in AmpersandProvider, which will accept either project ID or name
- Misc fixes & improvements for alternative auth
- Enable Save button when an Object doesn't require any configuration
> Release: update version to 1.8.0

- package.json
clean generated-sources/api before generating sources to delete old files.
> build: add clean-api script

- src/components/ApiKeyAuth/ApiKeyAuthFlow/ApiKeyAuthFlow.tsx
- src/components/BasicAuth/BasicAuthFlow/BasicAuthFlow.tsx
- src/components/NoAuth/NoAuthFlow/NoAuthFlow.tsx
- src/components/Oauth/WorkspaceEntry/WorkspaceOauthClientCredsFlow.tsx
recent changes from projectId remove from req object.
- remove projectId from GenerateConnectionRequest
> fix: remove unused projectId from request body

- generated-sources/api/.openapi-generator/FILES
- package.json
This updates the dependency to version [d92134e5e315f1c470fcb114cf8a2bfa3158d5f8](https://github.com/amp-labs/openapi/commit/d92134e5e315f1c470fcb114cf8a2bfa3158d5f8) from [main](https://github.com/amp-labs/openapi/tree/main)
> [auto] Update openapi dependency

- src/components/Oauth/NoWorkspaceEntry/NoWorkspaceOauthClientCredsFlow.tsx
> remove project id

- package.json
updates release version to 1.9.0 minor release
- add proxy onInstallSuccess support
- add scopes support for Oauth client credentials flow
- replace providerName with displayName
- adds doc links for auth flows
pending https://github.com/amp-labs/react/pull/486
> release: update version to 1.9.0

- package.json
- src/services/version.ts
- support backfill for UpdateInstallation
> Release: update version to 1.9.3

- src/components/Configure/nav/ObjectManagementNav/index.tsx
- src/components/Oauth/NoWorkspaceEntry/ClientCredentialsContent.tsx
- src/components/Oauth/NoWorkspaceEntry/LandingContent.tsx
- src/components/Oauth/OauthCardLayout/AmpersandFooter.tsx
- src/components/Oauth/OauthCardLayout/OauthCardLayout.tsx
- src/components/Oauth/Salesforce/SalesforceSubdomainEntry.tsx
- src/components/Oauth/WorkspaceEntry/ClientCredentialsContent.tsx
- src/components/Oauth/WorkspaceEntry/WorkspaceEntry.tsx
The Ampersand footer (logo) is added to the InstallIntegration component.
> [ENG-1539] feat: add ampersand footer to ObjectManagementNav

- package.json
Fixes typescript installations for devs.
> fix(package.json): add types to exports

- src/components/auth/Oauth/Salesforce/SalesforceSubdomainEntry.tsx
- src/components/ui-base/AccessibleLink/index.tsx
- src/components/ui-base/AccessibleLink/link.module.css
- src/styles/variables.css
remove chakra link from SalesforceSubdomainEntry. Adds bridge component `AccessibleLink`
> feat: add AccessibleLink component

- package.json
- src/components/auth/Oauth/NoWorkspaceEntry/LandingContent.tsx
- src/components/auth/Oauth/NoWorkspaceEntry/LandingContentProps.tsx
- src/components/auth/Oauth/NoWorkspaceEntry/NoWorkspaceEntryContent.tsx
- src/components/auth/Oauth/NoWorkspaceEntry/NoWorkspaceOauthFlow.tsx
- src/components/auth/Oauth/Salesforce/ChakraSalesforceSubdomainEntry.tsx
- src/components/auth/Oauth/Salesforce/SalesforceSubdomainEntry.tsx
- src/components/auth/Oauth/Salesforce/SubdomainEntryProps.tsx
- src/components/auth/Oauth/WorkspaceEntry/ChakraWorkspaceEntry.tsx
- src/components/auth/Oauth/WorkspaceEntry/WorkspaceEntryContent.tsx
- src/components/auth/Oauth/WorkspaceEntry/WorkspaceEntryProps.tsx
- src/components/auth/Oauth/WorkspaceEntry/WorkspaceOauthFlow.tsx
- src/components/form/Input/index.tsx
- src/components/form/Input/input.module.css
- src/components/form/index.ts
- src/components/ui-base/Button/button.module.css
- src/components/ui-base/Button/index.tsx
- src/layout/AuthCardLayout/AuthCardLayout.tsx
- src/styles/variables.css
- yarn.lock
refactor workspace entry component
- rename WorkspaceEntry to ChakraWorkspaceEntry
- extract WorkspaceEntryContent to use non-chakra components and WorkspaceEntryProps
- update WorkspaceOauthFlow to use WorkspaceEntryContent
> [ENG-1561] feat/refactor: refactor workspace entry component

- src/components/auth/Oauth/AuthorizationCode/WorkspaceEntry/Salesforce/ChakraSalesforceSubdomainEntry.tsx
- src/components/auth/Oauth/AuthorizationCode/WorkspaceEntry/Salesforce/SalesforceSubdomainEntry.tsx
- src/components/form/Input/input.module.css
- src/components/ui-base/Button/button.module.css
- src/styles/variables.css
Addresses feedback from https://github.com/amp-labs/react/pull/552
Merged earlier PR to unblock other PRs
> fix: address feedback to salesforce subdomain entry

- src/components/Configure/layout/ProtectedConnectionLayout.tsx
- src/components/auth/AuthCardLayoutTemplate.tsx
- src/components/auth/BasicAuth/BasicAuthContent.tsx
- src/components/auth/BasicAuth/BasicAuthFlow.tsx
- src/components/auth/BasicAuth/BasicAuthFlowProps.tsx
- src/components/auth/BasicAuth/ChakraLandingContent.tsx
- src/components/auth/BasicAuth/LandingContentProps.tsx
adds native implementation of basic auth flow and bridge component
> [ENG-1561] refactor: basic auth flow

- src/components/Configure/content/fields/FieldMappings/FieldMapping.tsx
removes some chakra components in FieldMapping.tsx
replacing the Select component
> [ENG-1579] refactor: remove chakra Stack and Text from FieldMapping.tsx

- src/components/Configure/content/UninstallContent.tsx
- src/components/ui-base/Button/button.module.css
- src/components/ui-base/Button/index.tsx
- src/styles/variables.css
remove chakra-ui from uninstall content
- adds native danger variant to button 
####
> [ENG-1578] refactor: rm chakra from uninstall content

- src/components/Configure/content/ConfigureInstallationBase.tsx
- src/components/auth/BasicAuth/ChakraLandingContent.tsx
- src/components/ui-base/Button/button.module.css
- src/components/ui-base/Button/index.tsx
- src/styles/variables.css
add bridge for native buttons in configure install base
- add button to configure installation base
- add ghost and hover state to button
> [ENG-1577] refactor: configure install base

- package.json
- src/components/Configure/content/fields/FieldMappings/FieldMapping.tsx
- src/components/Configure/content/fields/FieldMappings/RequiredFieldMappings.tsx
- src/components/ui-base/ComboBox/ComboBox.tsx
- src/components/ui-base/ComboBox/combobox.module.css
- src/styles/variables.css
- yarn.lock
adds native combobox component using downshift props.
- adds downshift
- adds combobox module css
- adds combobox component
- adds combobox to field mapping
- Test type ahead
- Test Button Toggle
- Test Menu Item hover
- Test Selection 
- Test Pre-fill
> [ENG-1593, ENG-1579] feat: add native combobox in field mapping

- package.json
- src/components/Configure/content/fields/OptionalFields/OptionalFields.tsx
- src/components/Configure/content/fields/OptionalFields/OptionalFieldsV2.tsx
- src/components/Configure/content/fields/OptionalFields/optionalFields.module.css
- src/styles/variables.css
- yarn.lock
Explores using radix to replace chakra components.
- add bridge to new optional fields component
- adds radix-ui checkbox to optional fields
> [ENG-1564, ENG-1581] feat/refactor: add native checkboxes to optional fields

- src/components/ui-base/Button/button.module.css
- src/styles/variables.css
update button style variables. make transparent variant white with box shadow
> [ENG-1588] style: update ghost button style

- src/components/Configure/content/ConfigureInstallationBase.tsx
- src/components/Configure/content/fields/OptionalFields/OptionalFields.tsx
- src/components/Configure/content/fields/WriteFields/WriteFields.tsx
- src/components/Configure/nav/ObjectManagementNav/index.tsx
- src/components/ui-base/Checkbox/checkbox.module.css
- src/components/ui-base/Checkbox/index.tsx
fix issue with overflow checkbox label
- fixes form widths
- ads word wrap in chakra and non-chakra checkboxes
> [ENG-1614] fix: adds checkbox word wrap

- src/components/ui-base/constant.ts
To test this in Mailmonkey inject 
```
REACT_APP_IS_CHAKRA_REMOVED=true
```
into env variable or start script like
```json
"start:prod": "PORT=3001 REACT_APP_AMP_SERVER=prod REACT_APP_IS_CHAKRA_REMOVED=true npm start",
```
> [ENG-1610] feat: add env ff to remove chakra-ui

- src/components/ui-base/constant.ts
- src/utils/index.ts
fix build by surrounding process.env in try catch
> fix/build: surround ff env var in try/catch

- src/components/ui-base/constant.ts
Feature flag fix. Even if the flag is false, the ff still turns on. Make ff explicit.
> fix: make feature flag check explicit check true

- package.json
- yarn.lock
Reverts amp-labs/react#630
In process of migration. This PR introduces breaking changes.
> Revert "build(deps-dev): bump @chakra-ui/react from 2.10.1 to 3.0.0"

- package.json
- src/components/Configure/nav/ObjectManagementNav/NavObjectItem.tsx
- src/components/Configure/nav/ObjectManagementNav/NavObjectItemProps.tsx
- src/components/Configure/nav/ObjectManagementNav/index.tsx
- src/components/ui-base/Tabs/index.tsx
- src/components/ui-base/Tabs/tabs.module.css
- src/styles/variables.css
- yarn.lock
This PR begins work on migrating Chakra Tabs. We create some dummy components for tabs including NavObject pending and completed state
- feat: add native tabs ui component
- does not include state management
- prepares a bridge component for ObjectManagementNav
https://github.com/amp-labs/react/pull/622
> [ENG-1616] feat: add radix tabs with some styling

- src/components/auth/Oauth/AuthorizationCode/OAuthWindow/OAuthWindow.tsx
This PR fixes the OAuth failed error that flashes before a successful connection. 
**Root cause:** Even when the connection is successful, the setInterval call was being multiple times due to re-renders. I wrapped it under a `useEffect` so it is now only called when the window `closed` status changes and no new intervals are created on re-renders. 
**Debugging:** 
**Test Screenshots (post-fix):**
**(on actual error)**
> [ENG-1599] fix: oauth error flashing before a successful connection

- src/components/Configure/content/UninstallCTA.tsx
- src/components/Configure/content/UninstallContent.tsx
- src/components/Configure/layout/ConditionalProxyLayout/ConditionalProxyLayout.tsx
- src/components/Configure/layout/ConditionalProxyLayout/InstalledSuccessBox.tsx
- src/components/Configure/layout/UninstallButton.tsx
This PR adds a button to uninstall the installation for a proxy only integration.
> [ENG-1598] feat: proxy-only installation should show option to uninstall

- src/components/auth/Oauth/AuthorizationCode/fetchOAuthPopupURL.ts
**DO NOT MERGE until backend changes are deployed**
> [ENG-1613] feat: ensure csrf cookies propagate to oauth callback 

- src/components/Configure/content/ConfigureInstallationBase.tsx
- src/components/FormCalloutBox.tsx
- src/styles/variables.css
adds FormCalloutBox component for displaying object mapping callout box. Logic is not included yet.
> [ENG-1650] feat: adds FormCalloutBox component

- src/components/Configure/content/fields/RequiredFields.tsx
problem: required field tags extended off page. add a flex-wrap.
> [ENG-1669] fix: tag wrapping

- src/components/auth/Oauth/OauthFlow/OauthFlow.tsx
I was asked to make this change ASAP. This enables the PKCE flow. It uses the same logic as authorization code, so there's really not a lot to do.
> feat: Enable authorizationCodePKCE flow

- src/components/auth/Oauth/AuthorizationCode/fetchOAuthPopupURL.ts
This PR adds support for PKCE OAuth grant types
> feat: Add PKCE support

- README.md
doc update for release of 2.0.0
> [ENG-1688] docs: update README.md to include import stylesheet

- src/components/Configure/content/UninstallContent.tsx
> style: replace quotes with bold style for appname in uninstall content

- src/components/Configure/content/fields/OptionalFields/optionalFields.module.css
- src/components/form/Input/input.module.css
- src/components/form/Textarea/textarea.module.css
- src/components/ui-base/Box/box.module.css
- src/components/ui-base/Button/button.module.css
- src/components/ui-base/Checkbox/checkbox.module.css
- src/components/ui-base/ComboBox/combobox.module.css
Removes hard coded white strings. Supports dark mode through theme override, but no dark mode in default is added yet (in progress https://github.com/amp-labs/react/pull/722/files). 
1. add the following file into mailmonkey as a app.css override
```css
:root {
color-scheme: light dark;
--amp-colors-white: light-dark(#ffffff, #1D1D1D);
--amp-colors-black: light-dark(#111111, #FDFCFD);
--amp-colors-primary: light-dark(#000000, #FFF);
/* Light color pallete */
--amp-colors-neutral-25-light: #FEFEFE;
--amp-colors-neutral-50-light: #FDFCFD;
--amp-colors-neutral-100-light: #FAFAFC;
--amp-colors-neutral-200-light: #F6F5F9;
--amp-colors-neutral-300-light: #F1EFF5;
--amp-colors-neutral-400-light: #EDEAF2;
--amp-colors-neutral-500-light: #E8E5EF;
--amp-colors-neutral-600-light: #918E95; …
```
> [ENG-1709] style: remove hard coded white background color

- src/components/Configure/InstallIntegration.tsx
- src/components/Connect/ConnectedSuccessBox.tsx
- src/context/ConnectionsContextProvider.tsx
- src/context/IntegrationListContextProvider.tsx
> fix: move integrationlist loading to InstallIntegration

- src/components/Configure/InstallIntegration.tsx
- src/context/ConnectionsContextProvider.tsx
- src/context/IntegrationListContextProvider.tsx
- src/context/ProjectContextProvider.tsx
> Revert "refactor: move project loading to Install Integration"

- src/components/Configure/InstallIntegration.tsx
- src/context/ConnectionsContextProvider.tsx
- src/context/IntegrationListContextProvider.tsx
- src/context/ProjectContextProvider.tsx
move the projectId error down below the loading.
> fix: ampersand loading in Connected Providers

- src/hooks/useIsIntegrationInstalled.ts
> Fix: bug where useIsIntegrationInstalled throws error

- src/components/ui-base/Button/button.module.css
update colors for delete and ghost button
> style: update button colors

- src/components/auth/ApiKeyAuth/ApiKeyAuthContent.tsx
> [ENG-1756] chore: replace placeholder text with API key

- src/components/auth/Oauth/AuthorizationCode/fetchOAuthPopupURL.ts
make CSRF opt in. 
@laurenzlong note the naming uses AMP for for the first 2 and APP for the last one.
```
VITE_AMP_ENABLE_CSRF
NEXT_AMP_ENABLE_CSRF
REACT_APP_ENABLE_CSRF
```
> [ENG-1746] build: make CSRF opt in.

- src/components/Configure/content/fields/ValueMapping/ValueMappingItem.tsx
Demo:  https://www.loom.com/share/b9f7c39e32ed4735a8def2b7c2e5ab5a?sid=3b6c649e-7da8-433c-81a2-eee00b0138fd
> [ENG-1768] fix: combobox glitch while selecting a value

- src/components/Configure/content/fields/FieldDefaultValueMapping/setValueDefaultWriteField.tsx
- src/components/Configure/content/fields/WriteFields/WriteFields.tsx
- src/components/Configure/content/fields/WriteFields/setNonConfigurableWriteField.tsx
- src/components/Configure/state/utils.ts
removes ff and does some renaming
> [ENG-1784] feat: remove field value defaults feature flag

- src/components/Configure/content/fields/ValueMapping/ValuesMapping.tsx
**Demo:**  https://www.loom.com/share/eb5cf7200b66470a823ddbbc1dc9d201 
**Test dynamic mapping config on `InstallIntegration` :**
```
const fieldMapping = {
contacts: [
{
mapToName: 'priority',
mapToDisplayName: 'Priority',
prompt: 'Which field do you use to track the priority of a deal?',
mappedValues: [
{
mappedValue: "X",
mappedDisplayValue: "X",
},
{
mappedValue: "Y",
mappedDisplayValue: "Y",
},
{
mappedValue: "Z",
mappedDisplayValue: "Z",
},
],
},
{
fieldName: "hs_email_customer_quarantined_reason",
mappedValues: [
{
mappedValue: "X",
mappedDisplayValue: "X",
},
{
mappedValue: "Y",
mappedDisplayValue: "Y",
},
{
mappedValue: "Z",
mappedDisplayValue: "Z",
},
],
},
{
mapToName: "territory",
mapToDisplayName: "Sales Territory",
prompt:
"Which field do you use to track the sales territory …
```
> [ENG-1813] feat: add value mapping for fields that are mapped

- src/components/Configure/content/fields/FieldMappings/DynamicFieldMappings.tsx
- src/components/Configure/content/fields/FieldMappings/OptionalFieldMappings.tsx
- src/components/Configure/content/fields/FieldMappings/RequiredFieldMappings.tsx
- src/components/Configure/content/fields/FieldMappings/index.ts
- src/components/Configure/content/fields/ReadFields.tsx
- src/components/Configure/content/fields/ValueMapping/ValuesMapping.tsx
**This PR has the following changes** 
1. moves dynamic field mappings into the optional fields section. 
2. Also fixes a bug where dynamic field mappings were accidentally being to set `null`
**Demo:** https://www.loom.com/share/860a4d1df5f3412bb8852276ed43ccdb
**Screenshot:** 
**Dynamic field mapping config:** 
```
const fieldMapping = {
contacts: [
{
mapToName: 'priority',
mapToDisplayName: 'Priority',
prompt: 'Which field do you use to track the priority of a deal?',
mappedValues: [
{
mappedValue: "X",
mappedDisplayValue: "X",
},
{
mappedValue: "Y",
mappedDisplayValue: "Y",
},
{
mappedValue: "Z",
mappedDisplayValue: "Z",
},
{
mappedValue: "A",
mappedDisplayValue: "A",
},
{
mappedValue: "B",
mappedDisplayValue: "B",
},
],
},
{
fieldName: "hs_email_customer_quarantined_reason", …
```
> [ENG-1810] chore: move dynamic field mapping to optional section

- src/components/auth/Oauth/AuthorizationCode/OAuthWindow/OAuthWindow.tsx
- src/components/auth/Oauth/AuthorizationCode/OAuthWindow/windowHelpers.tsx
Simplify connections logic in OauthWindow
- call invalidate connections cache on successful login
part 1: https://github.com/amp-labs/react/pull/847
1. gets connectionId from success event from our backend when user logs in
2. connectionId triggers a get connection call (refreshConnections call)
3. connection gets set to connections manager (no longer needed from part 1)
4. connections manager syncs selectedConnection with connections list (no longer needed from part 1)
1. same
2. connectionId still gets set for error purposes
3. invalidate cache to trigger refetch via react-query
```queryClient.invalidateQueries({ queryKey: ['amp', 'connections'] });```
4. connection is derived from connections list
> [ENG-1778, ENG-1837] refactor: simpilfy OAuthWindow connections logic (connections part 2)

- src/components/Configure/state/HydratedRevisionContext.tsx
migrate hydrated revision to use react-query
- replaces legacy api service
- conditional fetch
- cleans up useEffect
note: pending react-query being added into main. 
the new query is nested inside the provider, this might be able to be removed in the future since the hydrated revision is now accessible via the react-query global provider now.
> [ENG-1837] refactor: use react-query with hydrated revision

- src/components/Configure/layout/ProtectedConnectionLayout.tsx
Placeholder provider not found state is replace with proper loading and error state. 
- updates providerInfo to use react query and new api service
> [ENG-1911, ENG-1118] fix: provider not found bug

- src/components/auth/Oauth/AuthorizationCode/OAuthWindow/OAuthWindow.tsx
- src/components/auth/Oauth/AuthorizationCode/OAuthWindow/windowHelpers.tsx
> chore: update error message for oauth window

- src/components/Configure/content/UninstallContent.tsx
> chore: update uninstall description

- src/components/auth/BasicAuth/BasicAuthFlow.tsx
- src/components/auth/NoAuth/NoAuthFlow.tsx
- src/components/auth/useCreateConnectionMutation.ts
followup to https://github.com/amp-labs/react/pull/869
- migrate api service
- use react query
note: this flow is only used in testing.
> [ENG-1837] refactor: no auth flow

- src/components/Configure/content/fields/FieldMappings/FieldMapping.tsx
> chore: capitalize clear to Clear

- src/components/auth/Oauth/ClientCredentials/ClientCredentialsContainer.tsx
continues refactoring create connections in Client Credentials
- use react query
- migrate to unified api service
followup to https://github.com/amp-labs/react/pull/869/files
> [ENG-1837] refactor: client credentials flow

- src/components/Configure/content/fields/FieldMappings/DynamicFieldMappings.tsx
- src/components/Configure/content/fields/FieldMappings/FieldMapping.tsx
- src/components/Configure/content/fields/FieldMappings/OptionalFieldMappings.tsx
- src/components/Configure/content/fields/FieldMappings/RequiredFieldMappings.tsx
- src/components/Configure/content/fields/FieldMappings/checkDuplicateFieldError.tsx
**Demo:** https://www.loom.com/edit/f9eee922f93b4abda9812f10b04bd0b8 
**Screenshot:** 
**Also works between Required field mappings & across Optional & RequiredField mappings:**
**Remaining items on this PR:**
> [ENG-1803] feat: enforce 1:1 mapping for optional fields

- src/components/Configure/content/fields/FieldMappings/FieldMappingRow.tsx
- src/components/ui-base/ComboBox/ComboBox.tsx
combobox was experiencing issues where the selectedValue was not being updated. 
- fixes "Clear" again. 
fix: https://linear.app/getclarify/issue/ENG-3134/[ampersand]-selected-dropdown-option-should-be-black-not-grey
> fix: combobox select

- src/components/Configure/content/fields/ValueMapping/ValuesMapping.tsx
Refactors code for easier readability.
- reduces spacing
- adds conditions and variables for better readability
> refactor: values mapping

- src/components/Configure/content/fields/FieldDefaultValueMapping/FieldDefaultValueTable.tsx
- src/components/Configure/content/fields/FieldDefaultValueMapping/setValueDefaultWriteField.tsx
@laurenzlong - creating a draft for you to take over. These lines will need to match the new types whenever you're done with the type changes
> fix: default values type

- src/components/Configure/layout/UninstallButton.tsx
uses react query mutation hook to fire off delete installation. 
- no longer needs to call setInstallation manually 
- invalidates query cache to reset installations query
> [ENG-1837] refactor: migrate delete installation mutation (react-query)

- src/components/Configure/state/HydratedRevisionContext.tsx
hydratedRevision error fetches with old connectionId and does not clear error when connectionId is undefined. 
reset hydratedRevision query cache when connectionId is not available.
> fix: remove cached hydrated revision error

- src/components/ui-base/Button/button.module.css
- src/styles/variables.css
adds ability to override button font-size
> style: support custom text for button

- src/utils/handleServerError.ts
updates handle error to add error details and body, previously only looked at causes array which turn up empty sometimes.
> build: update handle error to look at details and remedy

- src/layout/AuthCardLayout/AmpersandFooter.tsx
add entitlement check to remove branding
> [ENG-2033] feat: add entitlement check to remove branding

- src/context/ProjectContextProvider.tsx
> [ENG-2033] feat: add includeEntitlements to getProject

- src/context/ConnectionsContextProvider.tsx
- src/hooks/query/useConnectionsListQuery.ts
refactors useConnectionsListQuery to prep for headless work
- move to hooks folder
- decouple from InstallIntegrationContextProvider
> [ENG-2100] refactor: useConnectionsListQuery

- src/context/IntegrationListContextProvider.tsx
- src/hooks/query/index.ts
- src/hooks/query/useIntegrationListQuery.ts
refactor useIntegrationListQuery
- move useIntegrationListQuery to hooks/query
- add queries to index file for export
> [ENG-2100] refactor: useIntegrationListQuery

- src/context/ConnectionsContextProvider.tsx
- src/hooks/query/useIntegrationQuery.ts
adds a placeholder useIntegrationQuery
- add provider from integration to useConnectionsListQuery
note: we need to update this to hit our endpoint directly.
> [ENG-2100] refactor: add useIntegrationQuery

- src/components/Configure/actions/mutateAndSetState/updateInstallationAndSetState.ts
- src/utils/index.ts
> [ENG-2046] chore: escape object names before creating config mask

- src/headless/installation/useDeleteInstallation.ts
- src/hooks/mutation/useDeleteInstallationMutation.ts
part 4 of adding headless installations manager
- adds shared mutation for delete installation
not tested. work in headless folder is not public.
> [ENG-2120] feat: add useDeleteInstallation mutation and headless hook

- src/components/Configure/content/ConfigureInstallationBase.tsx
- src/components/Configure/content/manage/ManageContent.tsx
- src/components/Configure/nav/ObjectManagementNav/constant.tsx
- src/components/Configure/nav/ObjectManagementNav/v2/Tabs/index.tsx
- src/components/Configure/nav/ObjectManagementNav/v2/index.tsx
Adds ui tab for update connections
- adds navigation to manage tab
- adds manage content placeholder
- adds feature flag to switch out uninstall and manage tabs
> feat: adds manage tab placeholder

- src/headless/installation/useCreateInstallation.ts
- src/headless/installation/useUpdateInstallation.ts
- src/hooks/mutation/useUpdateInstallationMutation.ts
adds update installation mutation and headless update installation hook
part 3 of https://linear.app/ampersand/issue/ENG-2106/[headless]-useinstallationsmanager
headless folder is not exposed to public. will be tested in future along side other installation hooks
> [ENG-2119] feat: add update installation hook

- src/components/Configure/content/manage/AuthenticationSection.tsx
- src/components/Configure/content/manage/ManageContent.tsx
- src/components/Configure/content/manage/authenticate.module.css
- src/headless/installation/useCreateInstallation.ts
- src/headless/installation/useUpdateInstallation.ts
- src/hooks/mutation/useUpdateInstallationMutation.ts
adds authenticate section for the manage tab. 
- shows connection workspace and status. 
- adds salesforce exception for subdomain
> [ENG-2147] feat: adds authentication section in manage tab

- src/components/Configure/content/manage/AuthenticationSection.tsx
- src/components/Configure/content/manage/ManageContent.tsx
- src/components/Configure/content/manage/authenticate.module.css
Accidently merged into another branch. Merge back into main.
https://github.com/amp-labs/react/pull/990
> feat: adds manage tab authentication section

- src/hooks/mutation/useUpdateConnectionMutation.ts
Part 2 in updating connection in InstallIntegration
this hook is not used anywhere yet. will be used and tested in a followup pr.
> [ENG-1418] feat: add useUpdateConnectionMutation hook

- src/components/Configure/content/manage/AuthenticationSection.tsx
- src/components/Configure/content/manage/ManageContent.tsx
- src/components/Configure/content/manage/UninstallSection.tsx
adds uninstall section to the manage tab content section 
- adjust spacing to align with the authenticate section
note: we will eventually delete the old uninstall content section
> [ENG-2152] feat: add uninstall section to manage tab

- src/components/Configure/content/manage/UninstallSection.tsx
hides uninstall section if user has not installed yet.
> feat: hide uninstall section if no installation

- src/components/Configure/content/manage/updateConnection/UpdateBasicAuthConnect.tsx
- src/components/Configure/content/manage/updateConnection/UpdateConnectionSection.tsx
- src/components/auth/BasicAuth/BasicAuthContent.tsx
adds basic auth update connection flow
- refactors basic auth form.
- form follows similar structure to client credentials and api key.
not end to end tested.
> [ENG-2169] feat: update basic auth connection

- src/hooks/useIsIntegrationInstalled.ts
requests so that builder knows which objects have been installed and plan accordingly.
> feat: add config to useIsIntegrationInstalled

- package.json
- yarn.lock
manually update typescript after eslint update
> build: update vite plugin and typescript

- src/components/auth/BasicAuth/BasicAuthContent.tsx
- src/components/auth/BasicAuth/BasicAuthFlow.tsx
- src/components/auth/BasicAuth/LandingContentProps.tsx
- src/components/auth/Oauth/AuthorizationCode/useOAuthPopupURL.ts
- src/services/version.ts
- yarn.lock
> feat: allow metadata as input

- yarn.lock
> Revert "build(deps-dev): bump @openapitools/openapi-generator-cli from 2.18.4 to 2.20.0"

- src/components/auth/ApiKeyAuth/ApiKeyAuthContent.tsx
> [#1089] fix: validation target

- src/components/auth/Oauth/AuthorizationCode/NoWorkspaceEntry/NoWorkspaceOauthFlow.tsx
- src/components/auth/Oauth/AuthorizationCode/OAuthWindow/OAuthWindow.tsx
- src/components/auth/Oauth/AuthorizationCode/OAuthWindow/windowHelpers.tsx
- src/components/auth/Oauth/AuthorizationCode/OauthFlow2/OauthFlow2.tsx
- src/components/auth/Oauth/AuthorizationCode/WorkspaceEntry/WorkspaceOauthFlow.tsx
- src/components/auth/Oauth/OauthFlow/OauthFlow.tsx
combines workspace and no-workspace oauth flow
pending hubspot oauth flow rework.
> refactor: combine workspace and no-workspace oauth flows

- src/headless/config/useConfigHelper.tsx
- src/headless/index.ts
- src/headless/types.ts
- adds advanced write features back to headless
- fixes some Enum exports 
https://github.com/amp-labs/demo-headless-write
> [ENG-2336] feat: add headless write features back

- src/components/Connect/ManageConnectionSection.tsx
- src/components/Connect/RemoveConnectionButton.tsx
- src/components/Connect/RemoveConnectionSection.tsx
- src/hooks/mutation/useDeleteConnectionMutation.ts
prep work to add remove connection to InstallIntegration component
> [ENG-2290] refactor: remove connection button

- src/components/ui-base/Checkbox/index.tsx
select all / indeterminate state is fixed.
> [ENG-1595] fix: select all / indeterminate state

- src/headless/manifest/useManifest.ts
fetches write object in the manifest
> [ENG-2342] feat: add write object to manifest

- src/components/Configure/layout/testdata.ts
- src/components/Docs/DocsHelperTextMinimal.tsx
- src/components/auth/CustomAuth/CustomAuthContent.tsx
- src/utils/index.ts
> [ENG-2356] style: update docs helper to be less crowded for custom auth

- src/headless/config/useConfigHelper.tsx
adds proxy support to headless
> [ENG-2369] feat: add proxy override support to headless useConfig

- src/components/Configure/InstallIntegration.tsx
adds an error message and component if user tries to use InstallIntegration with JWT.
> chore: add error message for JWT authentication in InstallIntegration

- src/components/Configure/actions/read/onSaveReadCreateInstallation.ts
- src/components/Configure/actions/write/onSaveWriteCreateInstallation.ts
per discussion - we're removing the FE responsibility in tracking revision id and shifting responsibility of revisionId to the backend
Create Write and Create Read test flows work.
> [ENG-2492] chore: remove revisionId from create installation config

- .github/workflows/npm-publish.yml
github action fails to build: requires node > v20
> chore: test workflow node 20
