amp-labs/react

- src/components/Configure/ObjectManagementNav/index.tsx
The uninstall button shows the wrong content because the feature flag doesn't add the correct length of buttons. This fixes the logic to allow feature flag logic.
> fix: fix feature flag write / uninstall case

- src/components/Configure/ObjectManagementNav/index.tsx
- src/components/Configure/content/fields/FieldMappings/FieldMapping.tsx
- src/components/Configure/content/fields/FieldMappings/RequiredFieldMappings.tsx
- src/components/Configure/content/fields/OptionalFields/OptionalFields.tsx
- src/components/Configure/content/fields/WriteFields/WriteFields.tsx
- src/components/Configure/content/fields/WriteFields/setNonConfigurableWriteField.tsx
- src/components/Configure/content/fields/useFields.tsx
- src/components/Configure/types.ts
- removes dummy data
- connects write form state to context
- refactors field state to use a `useField` hook. 
2. ~refactor read state~
3. ~add write state to context~
4. **connect data to write state slice** (in progress)
4a. **connect hydratedRevision data**
4b. connect config data
5. submit write state slice
6. add isModified / in progress state
> [ENG-512] feat: connect write form to state

- src/components/Configure/actions/onSaveReadCreateInstallation.ts
- src/components/Configure/actions/onSaveReadUpdateInstallation.ts
- src/components/Configure/content/ConfigureInstallationBase.tsx
- src/components/Configure/content/CreateInstallation.tsx
- src/components/Configure/content/UpdateInstallation.tsx
prepares for new feature of adding onSaveWrite by separating onSaveRead, this PR is separated to make it easier to review file name changes.
- feat: add write on save placeholders
- refactor: rename onSaveCreate to onSaveReadCreate and onSaveUpdate to onSaveReadUpdate
- fix some action types
> refactor: onSaveRead for create and update installation pages

- src/components/Configure/actions/onSaveWriteCreateInstallation.ts
- src/components/Configure/content/CreateInstallation.tsx
- src/components/Configure/state/ConfigurationStateProvider.tsx
- submits create installation 
- adds reset pending setter for write state
note: does not support update, pending, or completed interactions well after submit state yet.
2. ~refactor read state~
3. ~add write state to context~
4. ~connect data to write state slice~ 
4a. ~connect hydratedRevision data~
4b. connect config data
5. **submit write state slice**
5a. **submit create write installation**
5b. submit update write installation
6. ~add isModified / in progress state~
6b. complete, progress, empty state post submit.
> feat: adds onSaveWriteCreateInstallation action

- src/components/Configure/state/ConfigurationStateProvider.tsx
read state needs the objectname to change the form per object. 
`draft.other.read` does not exists.
> fix: pending state reset needs objectname

- src/components/Configure/actions/onSaveWriteCreateInstallation.ts
- src/components/Configure/state/utils.ts
- src/components/Configure/types.ts
This PR adds support for config pre-fill. When the component is refreshed, the form will pull data from both hydratedRevision and config now. 
2. ~refactor read state~
3. ~add write state to context~
4. ~connect data to write state slice~ 
4a. ~connect hydratedRevision data~
4b. **connect config data**
5. ~submit write state slice~
5a. ~submit create write installation~
5b. submit update write installation
7. ~add isModified / in progress state~
7b. progress, completed, non-completed state
> [ENG-512]feat: adds config pre-fill support

- src/components/Configure/actions/write/generateConfigWriteObjects.ts
- src/components/Configure/content/ConfigureInstallationBase.tsx
- src/components/Configure/content/UpdateInstallation.tsx
The save changes button doesn't work after the first time the update call is made. 
- update logic to add write fields which are in both the selected config and hydrated revision field list
- adds in a reset state when installation is updated (i.e. after a update installation returns successfully)
> fix: button not active when re-submitting update installation

- src/components/Configure/ObjectManagementNav/NavObjectItem.tsx
- src/components/Configure/ObjectManagementNav/OtherTab.tsx
- src/components/Configure/ObjectManagementNav/index.tsx
supports when only write is supported by the builder. 
text changes from 'other' to 'write'
> [ENG-587] feat: support only read and only write actions

- src/components/Connect/ConnectProvider.tsx
- src/components/Connect/OAuthPopup.tsx
- src/components/RedirectHandler/RedirectHandler.tsx
- src/components/RedirectHandler/index.ts
When redirectUrl param is present, the component will render a loading screen while redirecting to the URL. Otherwise, the child component will render.
- creates redirect handler component
1. enter in a relative url (i.e. `my.redirect.url`)
2. go to `http://localhost:3001/connect`
3. fill out provider credentials
4. observe loading and redirect when credentials accepted
> [ENG-524] feat: adds redirectUrl support to Connections Provider

- src/components/Configure/ProtectedConnectionLayout.tsx
- src/components/Connect/ConnectProvider.tsx
- src/components/Connect/ConnectedSuccessBox.tsx
- src/components/Connect/useConnectionHandler.tsx
creates onSuccess and onError hooks based on whether a connection has been established and whether a boundary error is triggered. 
- adds onSuccess connection handler
- adds onError connection handler for ConnectionList error
error only works for ConnectionList error. onErrors don't support other errors like subdomain errors, closing dialogue too early, etc... expected experience needs more clarity or to be returned back to support more onError scenarios.
- test by passing in an onSuccess in mailmonkey
- onError not fully tested yet
*NOTE: onError removed from PR*
> [ENG-524] feat: adds onSuccess connection handler

- src/context/InstallIntegrationContextProvider.tsx
The page will forever load if integration list is loaded but does not match an integration name. We now replace the loading icon with an error dialogue.
> [ENG-636] fix: replace loading with integration not found error message 

- src/components/Configure/InstallIntegration.tsx
- src/components/Configure/actions/onSaveReadUpdateInstallation.ts
- src/components/Configure/actions/write/onSaveWriteUpdateInstallation.ts
- src/components/Configure/content/UpdateInstallation.tsx
- src/components/Configure/content/useMutateInstallation.tsx
- src/context/InstallIntegrationContextProvider.tsx
adds support for onUpdateSuccess callback when update installation is successful. 
- supports read and write update installation
> [ENG-655] feat: adds onUpdateSuccess to InstallIntegration

- src/components/Configure/InstallIntegration.tsx
- src/components/Configure/actions/onSaveReadCreateInstallation.ts
- src/components/Configure/actions/onSaveReadUpdateInstallation.ts
- src/components/Configure/actions/write/onSaveWriteCreateInstallation.ts
- src/components/Configure/actions/write/onSaveWriteUpdateInstallation.ts
- src/components/Configure/content/CreateInstallation.tsx
- src/components/Configure/content/UpdateInstallation.tsx
- src/components/Configure/content/useMutateInstallation.tsx
- src/components/Connect/useConnectionHandler.tsx
- src/context/InstallIntegrationContextProvider.tsx
- adds success callback for when `<InstallIntegration/>` successfully calls createInstallation.   
- `read` and `write` support for onSaveCreateInstallation
> [ENG-655] feat: adds onInstallSuccess callback support

- src/components/Configure/nav/ObjectManagementNav/UninstallInstallation.tsx
- src/components/Configure/nav/ObjectManagementNav/index.tsx
- src/components/Configure/utils.ts
- src/components/RedirectHandler/RedirectHandler.tsx
- src/services/api.ts
Without special framework polyfilling, the react component doesn't work because of it's assumption that `process.env` exists. This PR fixes this as well as some typos I found.
> fix: assumptions around process.env and typos

- src/services/api.ts
I was still getting a process undefined error, this is because when the `process` variable is undefined `(process?.env?.REACT_APP_AMP_SERVER)` still hits a runtime error. To see this in action, just open up developer console in the browser, and type in `process?.env?.REACT_APP_AMP_SERVER`, you'll get `Uncaught ReferenceError: process is not defined`. But `typeof process === 'undefined'` is safe to run.
> fix: process undefined error

- src/services/api.ts
process is always undefined, current fix breaks local server development. 
we add try catch block to read env or return prod url if evaluation fails. not tested in embedded client yet.
> [ENG-733] fix: process.env.variable reference

- src/components/Configure/content/useMutateInstallation.tsx
- src/components/Configure/content/useSelectedConfigureState.tsx
- src/components/Configure/nav/ObjectManagementNav/index.tsx
- src/components/Configure/state/ConfigurationStateProvider.tsx
- src/components/Configure/state/utils.ts
If the user had a configuration that was empty, we would break react by creating an infinite loop. This has been resolved by adding a "null" state to differentiate between an unloaded object and an empty loaded object.
> fix: infinite loop if empty configuration state

- src/components/Configure/InstallIntegration.tsx
- src/components/Configure/layout/ConditionalProxyLayout.tsx
We need control logic to allow `<InstallIntegration/>` to skip configuration step if an installation only has proxy actions. This control sequence should activate if no read and no write is present in the hydratedRevision, but proxy actions also occur.
This PR creates the layout based which future PR's will
> [ENG-654] feat: add conditional proxy layout

- src/components/Configure/actions/proxy/isProxyEnabled.ts
- src/components/Configure/actions/read/onSaveReadCreateInstallation.ts
- src/components/Configure/actions/read/onSaveReadUpdateInstallation.ts
- src/components/Configure/actions/write/onSaveWriteCreateInstallation.ts
- src/components/Configure/actions/write/onSaveWriteUpdateInstallation.ts
- src/components/Configure/content/UpdateInstallation.tsx
We need to support proxy when read and write are configured. 8 cases of combinations to be supported
- support **read create installation** with/without proxy enabled
- support **write create installation** with/without proxy
- support **read update installation** with/without proxy
- support **write update installation** with/without proxy
UI should have no visible changes
- locally: read/write create/update with proxy. 
- production: read/write create/update without proxy.
> [ENG-732] feat: support proxy enabled read / write

- package.json
- src/services/api.ts
- src/services/version.ts
NOTE: I wrote this to match the header names being sent by the cli application. It's important to keep the names consistent.
Once we have our UI libraries out in the wild, we want to keep track of the versions that are still being used. Similar to how the CLI always adds a header to indicate which CLI version made an API call, we should do the same in the React SDK. 
The first task here is the centralize how API request are made in the UI library, we probably need to introduce a uesAPI method [similar to the one in the Console](https://github.com/amp-labs/client/blob/07032b2469b1d60d19369a0bfd2d5cef8136e157/src/data/api.ts#L13), then that method can always add the following headers:
X-Amp-Client-Application : React
alternatives: X-Amp-Client-Platform, X-Amp-Client-Flavor, …
> [ENG-831] feat: automatically add a few headers to client calls

- src/components/Configure/layout/ProtectedConnectionLayout.tsx
- src/components/Oauth/WorkspaceEntry/WorkspaceEntry.tsx
- src/components/Oauth/WorkspaceEntry/WorkspaceOauthFlow.tsx
We want to support generic providers that require workspaces. We will keep parts of the SalesforceEntry as having a custom entry for large provider may prove useful.
- add `WorkspaceEntry` component
- adds `WorkspaceOauthFlow` and feature flag
When we turn on the flag, salesforce will use the generic WorkspaceEntryFlow component instead of the existing custom flow. 
Some of the forms can be refactored and deleted so there is less copy pasted styles.
> [ENG-930, ENG-932] feat: add generic WorkspaceOauthFlow component 

- src/components/Configure/layout/ProtectedConnectionLayout.tsx
- src/components/Oauth/OauthFlow/OauthFlow.tsx
Separate the Oauth flow logic from the connections logic. We will be able to add our provider api calls and logic to choose which flow to render in this new component. 
preps for [ENG-931]
no visible UI changes to demo.
> [ENG-931] refactor: Oauthflow logic from ProtectedConnectionLayout

- .github/workflows/lint.yml
In #272, code that did not build (outside of my machine) managed to land in main because we didn't check that the code was buildable in the CI environment. This PR simply checks that the code is able to build correctly during linting.
> [ENG-726] ci: check that the project is buildable

- src/components/Configure/nav/ObjectManagementNav/index.tsx
- src/components/ErrorTextBox.tsx
- src/components/Oauth/OauthCardLayout.tsx
- src/components/SuccessTextBox.tsx
When embedders use @amp-labs/react, the styling of their website leaked into the components in such a way that text could appear invisible (white-on-white). 
Before:
After:
> [ENG-731] fix: styling issue with text color on white background

- src/components/Oauth/NoWorkspaceEntry/NoWorkspaceOauthFlow.tsx
- src/components/Oauth/WorkspaceEntry/WorkspaceOauthFlow.tsx
- src/components/Oauth/fetchOAuthCallbackURL.ts
When component did not have `consumerName` the app failed to launch the Oauthflow. We remove the if checks and go to the try catch so errors will be handled in the catch loop. We also make `groupName` optional.
> fix: allow groupName and consumerName to be optional

- src/components/Configure/nav/ObjectManagementNav/index.tsx
- src/components/Configure/state/utils.ts
- src/components/Configure/utils.ts
Customer bug: when write is the only tab, the object state is not reset properly. 
Root problem: reseting state made a call to `generateNavObjects` which under the hood only fetched read nav objects. We rename this and also fetch all objects under the new function. We keep the nav objects separate for the tab divider in the left hand selector.
- changes tested under both `write only` (`writeSalesforceCustomObjects`) and `read and write`(`name:p0-i3`) salesforce integrations in dev.
```
const projectId = '5e4f06ca-445f-43ea-943e-78465ee1bb7a';
const apiKey = 'TASW3OD2BOY252UQHFUK53FHHFDXBP6YHQFKN2A';
const integration = 'writeSalesforceCustomObjects'; 
```
> fix: nav objects were not resetting write state on load

- src/components/Configure/content/ConfigureInstallationBase.tsx
- src/components/Configure/content/fields/WriteFields/WriteFields.tsx
Customer is asking to support select all support for write fields since there are a lot of fields. We add this option for 2 or more fields in selection
- adds select all functionality
- adds indeterminate state
- adds isAllChecked state
- modifies spacing so there is no awkward space in checkbox list and creates min height in outer box. 
- fix checkmark box styling and padding
> feat: add select all button to write fields

- src/components/Configure/content/fields/OptionalFields/OptionalFields.tsx
Checkbox spacing looks uneven. We adjust styles to match spacing update in read fields.
To test you can use `const integration = 'name:p0-i3'` in mailmonkey.
> style: update checkbox spacing in optional fields

- generated-sources/api/.openapi-generator/FILES
- generated-sources/api/src/models/BaseReadConfig.ts
- generated-sources/api/src/models/BaseReadConfigObject.ts
- generated-sources/api/src/models/HydratedIntegrationRead.ts
- generated-sources/api/src/models/IntegrationRead.ts
- generated-sources/api/src/models/index.ts
- src/components/Configure/actions/mutateAndSetState/updateInstallationAndSetState.ts
- src/components/Configure/actions/read/onSaveReadCreateInstallation.ts
- src/components/Configure/actions/read/onSaveReadUpdateInstallation.ts
- src/components/Configure/actions/write/onSaveWriteCreateInstallation.ts
- src/components/Configure/content/UpdateInstallation.tsx
- src/components/Configure/state/utils.ts
- src/components/Configure/utils.ts
See [ Slab doc](https://ampersand.slab.com/posts/changing-read-standard-objects-to-read-objects-38flho3m) for context. 
This PR was tested against https://github.com/amp-labs/server/pull/964 and I manually verified:
- creating installation
- updating installation
> [ENG-916] breaking: transition from `read.standardObjects` to `read.objects`

- package.json
- tsconfig.json
- vite.config.ts
- yarn.lock
This PR adds vite as a build tool.
- adds vite dependency
- vite define config file
- updates package.json to use vite commands to compile into CommonJs and ES module files.
- adds ts types into a single export file.
Our library build support relies mostly on basic eslint, babel, and typescript to compile down into common js to be most compatible. One of the downsides is not being able to leverage some of the debugging capabilities and ease of readability in ES module syntax. This PR primarily grants support for both. Vite will also provide additional tooling support around packages and aliases which are not supported yet in these repo.
vite library mode: https://vitejs.dev/guide/build#library-mode
vite supports rollup bundling: https://rollupjs.org/ 
- updates to the code seems to break …
> build: update build process to use vite library mode

- .eslintrc.cjs
- .gitignore
- package.json
- vite.config.ts
- yarn.lock
adds a bundle analyze plugin to give us a bundle size snapshot
- adds `yarn analyze` script
- allows imports from [devDependencies in eslint](https://stackoverflow.com/questions/44939304/eslint-should-be-listed-in-the-projects-dependencies-not-devdependencies)
The bundle analyzer will give us a snapshot of what our library outputs. This is useful in seeing our own dependencies, code, and whether packages should be moved to peer dependences or imported directly.
run `yarn analyze` to see snapshot
- React (core) + React DOM: ~120 KB (minified and gzipped)
- Clerk Bundle Size [~1mb.](https://github.com/clerk/javascript/issues/1578) - when importing react.
- remove `chakra-ui/icons` as a dependency. We use 1 icon and the package is 15% of our bundle size. We can either require it to be …
> build: adds vite bundle analyzer

- src/context/ConnectionsContextProvider.tsx
- src/context/InstallIntegrationContextProvider.tsx
- src/context/IntegrationListContextProvider.tsx
- src/context/ProjectContextProvider.tsx
- src/hooks/useIsIntegrationInstalled.ts
- src/services/ApiService.ts
- src/services/api.ts
- src/services/version.ts
- tsconfig.json
- vite.config.ts
- adds alias for generated-sources
- adds alias for components, hooks, services, context
Adds alias for non-component folders. 
Will add aliases to component folder.
> build: add path alias for vite to tsconfig

- .eslintrc.cjs
- src/components/Oauth/OAuthWindow/OAuthWindow.tsx
- src/components/Oauth/OAuthWindow/windowHelpers.tsx
Now that there's more people contributing to the codebase, we should make our linters more strict to catch potential errors. I've added the `react-hooks/rules-of-hooks` linter and made `react-hooks/exhaustive-deps` error instead of warn because warn doesn't get caught by Github Actions, and if there's a legitimate reason for not having exhaustive deps in a `useEffect` a `nolint` line can be added.
> Add rule-of-hooks linter and make exhaustive-hooks linter error not warn

- src/context/AmpersandContextProvider/AmpersandContextProvider.tsx
- src/context/IntegrationListContextProvider.tsx
- src/context/ProjectContextProvider.tsx
Now `projectId` is deprecated (optional) for `project`. 
Also added runtime console errors when no `project` or `apiKey` is provided
> [ENG-1296] feat: deprecate `projectId` for `project`

- src/components/Configure/content/ConfigureInstallationBase.tsx
The current configure component requires a dirty state or create state to enable submit. This PR adds a check to see if the object has been completed, if not completed as a read state, it will be considered a new state so disable will not be activated
- adds check if selected object is completed, before enabling disable.
`amp.yaml`
```
specVersion: 1.0.0
integrations:
- name: readHubspotContactsRequiredOnly2
displayName: Read Hubspot Contacts
provider: hubspot
read:
objects:
- objectName: contact
destination: defaultWebhook
schedule: "*/30 * * * *" # Every 30 minutes
requiredFields:
- fieldName: name    
- objectName: account
destination: defaultWebhook
schedule: "*/30 * * * *" # Every 30 minutes
requiredFields:
- fieldName: name
```
tests working with other optional read/ write …
> [ENG-1407] fix: allow required only reads to be saved

- Dockerfile
This introduces a builder image. This is necessary to create automations, such as a cloudbuild trigger to automatically update generated sources with the latest openapi definitions.
> feat: Add a builder image

- src/components/Oauth/NoWorkspaceEntry/ClientCredentialsContent.tsx
- src/components/Oauth/NoWorkspaceEntry/NoWorkspaceOauthClientCredsFlow.tsx
- src/components/Oauth/OauthFlow/OauthFlow.tsx
- src/components/Oauth/WorkspaceEntry/ClientCredentialsContent.tsx
- src/components/Oauth/WorkspaceEntry/WorkspaceOauthClientCredsFlow.tsx
- src/utils/index.ts
Adds scopes support to UI Oauth client credentials flow.
- add scopes to NoWorkspaceEntry, WorkspaceEntry
- add convertTextareaToArray to utils
- moves magic strings into variables
There's similar code that can be refactored across the flows.
> [ENG-1453] feat: add scopes support for Oauth client credentials flow

- src/components/Configure/layout/ConditionalProxyLayout/ConditionalProxyLayout.tsx
`onInstallSuccess` side effect is not activated in proxy yet. This PR adds support for calling the side effect.
```
<InstallIntegration
integration={integration}
consumerName={userName}
consumerRef={userId}
groupRef={groupId}
groupName={groupName}
onInstallSuccess= {(installationId: string, configObject: any) => {
console.log("TESTING INSTALLATION: proxy enabled.");
console.log(`Successfully installed ${installationId} with configuration ${JSON.stringify(configObject, null, 2)}`)}                              
}
onUpdateSuccess = {(installationId: string, configObject: any) =>{
console.log(`Successfully updated ${installationId} with configuration ${JSON.stringify(configObject, null, 2)}`)}
}                    
/>
```
> [ENG-1475] feat: support proxy onInstallSuccess

- src/components/Configure/actions/read/onSaveReadUpdateInstallation.ts
- src/services/api.ts
backfill is supported in createInstallation (proxy and read), but not update. 
- add backfill support to updateInstallation (read), proxy has no update 
- followup to https://github.com/amp-labs/react/pull/451
I'm unsure if write create/update installation backfill needs support in ui library. This support would be a separate ticket if so.
> [ENG-1515] feat: add backfill support to update read installation

- generated-sources/api/src/models/CreateIntegrationRequestLatestRevision.ts
This updates the dependency to version [46ebdd981ea9fd3138348375e1ba4f5294619eff](https://github.com/amp-labs/openapi/commit/46ebdd981ea9fd3138348375e1ba4f5294619eff) from [main](https://github.com/amp-labs/openapi/tree/main)
> [auto] Update openapi dependency

- src/components/ApiKeyAuth/ApiKeyAuthFlow/LandingContent.tsx
- src/components/BasicAuth/BasicAuthCardLayout.tsx
- src/components/BasicAuth/BasicAuthFlow/LandingContent.tsx
- src/components/Configure/content/ConfigureInstallationBase.tsx
- src/components/Configure/nav/ObjectManagementNav/index.tsx
- src/components/NoAuth/NoAuthFlow/LandingContent.tsx
- src/components/Oauth/NoWorkspaceEntry/ClientCredentialsContent.tsx
- src/components/Oauth/NoWorkspaceEntry/LandingContent.tsx
- src/components/Oauth/Salesforce/SalesforceSubdomainEntry.tsx
- src/components/Oauth/WorkspaceEntry/ClientCredentialsContent.tsx
- src/components/Oauth/WorkspaceEntry/WorkspaceEntry.tsx
- src/components/ThemeProvider/Button/buttonTheme.ts
- src/components/ThemeProvider/index.tsx
This PR attempts to update styles to better "smart defaults". 
- make colors more muted
- update button styles to be black/gray
- reduces border radius and shadows to be less pronounced.
- adds a primary button variant
- removes default chakra/fb styling
> style: update defaults to be less bold

- src/components/Configure/content/UninstallContent.tsx
- src/components/Configure/layout/ConditionalProxyLayout/ConditionalProxyLayout.tsx
- src/context/InstallIntegrationContextProvider.tsx
- src/hooks/useIsInstallationDeleted.ts
Uninstall integration UX is a little unclear as the form still exists with an uninstall message. This replaces the component with an Uninstall Success Box. 
- adds terminal state after uninstalling an integration
context: https://ampersand-company.slack.com/archives/C06NLLVMXU7/p1725915995197509?thread_ts=1725877852.982429&cid=C06NLLVMXU7
> [ENG-1533] feat: add a uninstalled success box

- src/components/Configure/InstallIntegration.tsx
- src/components/Configure/content/UninstallContent.tsx
- src/context/InstallIntegrationContextProvider.tsx
the `onUninstallSuccess` prop will enable builders to pass in a callback from their application (i.e. page navigation or cleaning up their connections)
- supports uninstall installation callback as a prop
add in documentation
```js
<InstallIntegration
integration={integration}
consumerName={userName}
consumerRef={userId}
groupRef={groupId}
groupName={groupName}
onInstallSuccess= {(installationId: string, configObject: any) => {
console.log(`Successfully installed ${installationId} with configuration ${JSON.stringify(configObject, null, 2)}`)}                              
}
onUpdateSuccess = {(installationId: string, configObject: any) =>{
console.log(`Successfully updated ${installationId} with configuration ${JSON.stringify(configObject, null, 2)}`)}
} …
```
> [ENG-1532] feat: add onUninstallSuccess in InstallIntegration

- src/components/Oauth/NoWorkspaceEntry/ClientCredentialsContent.tsx
- src/components/Oauth/NoWorkspaceEntry/LandingContent.tsx
- src/components/Oauth/OauthCardLayout/AmpersandFooter.tsx
- src/components/Oauth/OauthCardLayout/OauthCardLayout.tsx
- src/components/Oauth/Salesforce/SalesforceSubdomainEntry.tsx
- src/components/Oauth/WorkspaceEntry/ClientCredentialsContent.tsx
- src/components/Oauth/WorkspaceEntry/WorkspaceEntry.tsx
adds Ampersand logo to login component. Logo directs to ampersand website. 
- adds AmpersandFooter component
- moves OauthCardLayout to its own folder
- updates references to OauthCardLayout
note: css.modules are not supported yet.
> [ENG-1538] feat: adds ampersand footer to oauth card layout

- src/components/Oauth/NoWorkspaceEntry/NoWorkspaceOauthFlow.tsx
- src/components/Oauth/OAuthWindow/OAuthWindow.tsx
- src/components/Oauth/OAuthWindow/windowHelpers.tsx
- src/components/Oauth/WorkspaceEntry/WorkspaceOauthFlow.tsx
Bring back granular error handling. 
- renames onClose to onError since we can perform errors without closing the window.
note: did not replicate, will need help to set up local env to mimic this error.
> [ENG-1350] fix: bring back more granular error handling for auth errors

- package.json
- src/components/Oauth/OauthCardLayout/OauthCardLayout.tsx
- src/components/ui-base/Box/Box.tsx
- src/components/ui-base/Box/box.module.css
- src/components/ui-base/constant.ts
- src/global.d.ts
- src/index.ts
- src/styles/variables.css
- yarn.lock
Chakra UI has served as a powerful tool to get the embedded library bootstrapped. However, the advanced tooling and ease of use come at the cost of less flexibility, reliant dependencies, and issues related to [emotion](https://dev.to/srmagura/why-were-breaking-up-wiht-css-in-js-4g9b). This PR demos the migration process using the Chakra-UI `Box`. 
During the process of vetting alternative solutions, the author of Chakra-UI has indicated that two things need to be used to [replace chakra-ui](https://www.adebayosegun.com/blog/the-future-of-chakra-ui).
1. a headless library ([ark](https://ark-ui.com/), [radix](https://www.radix-ui.com/), shadcn, react-aria...)
2. a styling solution. ([panda](https://panda-css.com/), [vanilla extract](https://vanilla-extract.style/), etc...)
The last few …
> [ENG-1516] poc: css migration to remove chakra

- src/components/Configure/content/ConfigureInstallationBase.tsx
- src/components/Configure/layout/ConditionalProxyLayout/ConditionalProxyLayout.tsx
- src/components/Loading/LoadingIcon.tsx
- src/components/Loading/index.tsx
- src/components/Loading/style.module.css
- src/components/RedirectHandler/RedirectHandler.tsx
- src/components/auth/Oauth/NoWorkspaceEntry/NoWorkspaceOauthClientCredsFlow.tsx
- src/components/auth/Oauth/WorkspaceEntry/WorkspaceOauthClientCredsFlow.tsx
- src/context/ConnectionsContextProvider.tsx
- src/context/InstallIntegrationContextProvider.tsx
- src/context/IntegrationListContextProvider.tsx
- src/context/ProjectContextProvider.tsx
- src/styles/variables.css
adds bridge component for loader. 
- swap chakra for css loader that matches client loader
- move to components/loading
> feat/refactor: update to new loading component

- src/components/Configure/content/fields/FieldHeader.tsx
- src/components/Configure/nav/ObjectManagementNav/OtherTab.tsx
- src/components/Configure/nav/ObjectManagementNav/index.tsx
- src/components/ui-base/Divider/divider.module.css
- src/components/ui-base/Divider/index.tsx
- src/styles/variables.css
add bridge Divider component
- creates a bridge Divider component with custom css
- swaps all existing Divider components with the new bridge Divider component
- swaps out Box and Container in ObjectManagmentNav component
> feat: add bridge Divider component

- src/components/Configure/content/ConfigureInstallationBase.tsx
- src/components/Configure/content/fields/FieldHeader.tsx
- src/components/Configure/content/fields/FieldMappings/FieldMapping.tsx
- src/components/Configure/content/fields/FieldMappings/RequiredFieldMappings.tsx
- src/components/Configure/content/fields/RequiredFields.tsx
- src/styles/variables.css
Removes more chakra layout components and simplify html structure by removing unnecessary divs, flex boxes, and stacks. 
- remove chakra-ui box, flex from components: ConfigureInstallationBase.tsx, RequiredFieldMappings.tsx, RequiredFields.tsx
- update some imports
- adds dynamic css fallback for css variables that may not exists during migration 
```js 
// example dynamics css
const boxShadow = getComputedStyle(document.documentElement)
.getPropertyValue('--amp-shadows-sm').trim() || '0 1px 2px 0 rgba(0, 0, 0, 0.05)';
```
no css files were added, inline style serves as an alternative styling solution
> refactor: removes chakra from FieldHeader and other components

- src/components/Configure/content/ConfigureInstallationBase.tsx
- src/components/FormErrorBox.tsx
adds native error form box component and demos in installation form
- does not include error handling logic yet
> [ENG-1485] feat: add error box UI to installation form 

- src/components/Configure/content/fields/RequiredFields.tsx
- src/components/ui-base/Tag/index.tsx
- src/styles/variables.css
removes the tag component, adds native Tag component with updated grayscale.
> refactor: rm chakra-ui tag, add custom tag component

- src/components/auth/Oauth/OAuthWindow/OAuthWindow.tsx
- src/services/ApiService.ts
We'll be introducing frontend-only API keys soon, which will have less access than full API keys. This PR removes unnecessary API services from from being exported.
> chore: remove unused API services

- src/components/auth/AuthErrorAlert/AuthErrorAlert.tsx
refactor: remove chakra-ui from AuthErrorAlert
> [ENG-1563] refactor: remove chakra-ui from AuthErrorAlert

- package.json
- src/components/auth/Oauth/Salesforce/ChakraSalesforceSubdomainEntry.tsx
- src/components/auth/Oauth/Salesforce/SalesforceSubdomainEntry.tsx
- src/components/auth/Oauth/Salesforce/SubdomainEntryProps.tsx
- src/components/form/Input/index.tsx
- src/components/form/Input/input.module.css
- src/components/form/index.ts
- src/components/ui-base/Button/button.module.css
- src/components/ui-base/Button/index.tsx
- src/styles/variables.css
- yarn.lock
refactor SalesforceSubdomainEntry to not use Chakra. Adds bridge Component to swap out Chakra implementation.
- add native button
- add native input
- mv salesforce subdomain entry to chakra file (deprecated)
> [ENG-1561] feat/refactor: salesforce subdomain entry component

- src/components/auth/Oauth/NoWorkspaceEntry/LandingContent.tsx
- src/components/auth/Oauth/NoWorkspaceEntry/LandingContentProps.tsx
- src/components/auth/Oauth/NoWorkspaceEntry/NoWorkspaceEntryContent.tsx
- src/components/auth/Oauth/NoWorkspaceEntry/NoWorkspaceOauthFlow.tsx
- src/components/auth/Oauth/Salesforce/SalesforceSubdomainEntry.tsx
- src/components/ui-base/Button/button.module.css
- src/layout/AuthCardLayout/AuthCardLayout.tsx
refactors no workspace entry form
- add NoWorkspaceEntryContent component to replace LandingContent
- deprecate LandingContent (chakra-ui)
> [ENG-1561] feat/refactor: no workspace entry

- package.json
- src/components/auth/Oauth/ClientCredentials/NoWorkspaceClientCredentialsContent.tsx
- src/components/auth/Oauth/ClientCredentials/NoWorkspaceOauthClientCredsFlow.tsx
- src/components/auth/Oauth/ClientCredentials/WorkspaceClientCredentialsContent.tsx
- src/components/auth/Oauth/ClientCredentials/WorkspaceOauthClientCredsFlow.tsx
- src/components/auth/Oauth/NoWorkspaceEntry/LandingContent.tsx
- src/components/auth/Oauth/NoWorkspaceEntry/LandingContentProps.tsx
- src/components/auth/Oauth/NoWorkspaceEntry/NoWorkspaceEntryContent.tsx
- src/components/auth/Oauth/NoWorkspaceEntry/NoWorkspaceOauthFlow.tsx
- src/components/auth/Oauth/OauthFlow/OauthFlow.tsx
- src/components/auth/Oauth/Salesforce/ChakraSalesforceSubdomainEntry.tsx
- src/components/auth/Oauth/Salesforce/SalesforceSubdomainEntry.tsx
- src/components/auth/Oauth/Salesforce/SubdomainEntryProps.tsx
- src/components/auth/Oauth/WorkspaceEntry/ChakraWorkspaceEntry.tsx
- src/components/auth/Oauth/WorkspaceEntry/WorkspaceEntryContent.tsx
- src/components/auth/Oauth/WorkspaceEntry/WorkspaceEntryProps.tsx
- src/components/auth/Oauth/WorkspaceEntry/WorkspaceOauthFlow.tsx
- src/components/form/Input/index.tsx
- src/components/form/Input/input.module.css
- src/components/form/index.ts
- src/components/ui-base/Button/button.module.css
- src/components/ui-base/Button/index.tsx
- src/layout/AuthCardLayout/AuthCardLayout.tsx
- src/styles/variables.css
- yarn.lock
The client credential folder structure is confusing with a copy of it's own form in both workspaces and no workspaces. This PR starts simplifying the auth flows by moving `ClientCredentials` in it's own folder. This will let us deduplicate form code and start organizing auth by grant type. 
This work is needed to more easily delete copied chakra code. 
```js
Oauth
- AuthorizationCode // grant type
-- Workspace
--- SalesforceSubDomain
-- NoWorkspace
- ClientCredentials // grant type
// todo: deduplicate ClientCredentialsContent
-- Container
-- Content
- OauthFlow // choose which grant type
```
1. move files around to organize my grant type
2. deduplicate and simplify oauth flow logic
> [ENG-1561] refactor: move client credentials grant type to own dir

- src/components/auth/Oauth/ClientCredentials/ClientCredentials.tsx
- src/components/auth/Oauth/OauthFlow/OauthFlow.tsx
Now that client credentials is it's own folder, we'll move logic to pick which client crediential form to show into it's own folder and simplify the top level oauth flow file. 
- simplify shared props across oauth flows
- add client credentials flow to prep Chakra swap
Follow up to: https://github.com/amp-labs/react/pull/557
> [ENG-1561] refactor: add client credentials flow

- src/components/auth/Oauth/ClientCredentials/ClientCredentialsContent.tsx
- src/components/form/Textarea/index.tsx
- src/components/form/Textarea/textarea.module.css
- src/components/form/index.ts
adds a native Textarea component, removes from ClientCredentials.
> [ENG-1561] feat: add Textarea component

- src/components/auth/AuthCardLayoutTemplate.tsx
- src/components/auth/NoAuth/ChakraLandingContent.tsx
- src/components/auth/NoAuth/LandingContentProps.tsx
- src/components/auth/NoAuth/NoAuthContent.tsx
- src/components/auth/NoAuth/NoAuthFlow.tsx
adds a native implementation of NoAuthFlow
- adds a template that assembles AuthCardLayout, title, buttons, and content
- renames LandingContent to ChakraLandingContent
> [ENG-1561] refactor: NoAuthFlow to use AuthCardLayoutTemplate

- src/components/auth/ApiKeyAuth/ApiKeyAuthContent.tsx
- src/components/auth/ApiKeyAuth/ApiKeyAuthFlow.tsx
- src/components/auth/ApiKeyAuth/ChakraLandingContent.tsx
- src/components/auth/ApiKeyAuth/LandingContentProps.tsx
- src/components/auth/BasicAuth/BasicAuthContent.tsx
- src/components/auth/BasicAuth/BasicAuthFlow.tsx
- src/components/auth/BasicAuth/LandingContentProps.tsx
Refactoring Auth forms continues. 
- deprecated ChakraLandingContent.tsx (ApiKeyAuth)
- renamed LandingContent.tsx to ChakraLandingContent.tsx (ApiKeyAuth)
- added LandingContentProps.tsx (ApiKeyAuth)
- add bridge component ApiKeyAuthContent.tsx (ApiKeyAuth)
Chakra form will still be live when feature flag is turned off.
> [ENG-1561] refactor: ApiKeyAuth to use native form elements

- src/components/auth/BasicAuth/ChakraLandingContent.tsx
fix build error
```
src/components/auth/BasicAuth/ChakraLandingContent.tsx:88:28 - error TS2353: Object literal may only specify known properties, and 'username' does not exist in type 'BasicCreds'.
88             handleSubmit({ username, password });
~~~~~~~~
```
> fix: handle submit type

- src/components/RedirectHandler/RedirectHandler.tsx
- src/components/RedirectHandler/RedirectLoading.tsx
- removes chakra-ui from redirect handler
- adds RedirectLoading component
> [ENG-1575] refactor: remove chakra from RedirectHandler

- src/components/Docs/DocsHelperText.tsx
remove chakra-ui from docs helper text in auth flows.
> [ENG-1576] refactor: rm chakra from docs helper text

- src/components/Configure/content/fields/OptionalFields/OptionalFieldsV2.tsx
- src/components/ui-base/Checkbox/checkbox.module.css
- src/components/ui-base/Checkbox/index.tsx
Makes checkboxes into it's own component to be used outside of OptionalFields
- move the checkbox component to ui-base
- shared styles
followup to: https://github.com/amp-labs/react/pull/600
> [ENG-1564] refactor: componentize the checkbox component

- src/components/Configure/InstallIntegration.tsx
- src/components/Configure/layout/ConditionalProxyLayout/ConditionalProxyLayout.tsx
- src/components/SuccessTextBox/SuccessTextBox.tsx
Users are asked to delete and re-install integration when connection id or something is not set correctly. We need to support reinstallation in the UI lib.
- adds button when installation is deleted. 
- reinstall button will trigger a seed refresh and force the InstallIntegration component to re-render. 
As a side note, this logic can be forced during the onUninstallIntegration callback in the parent app. 
note: this is hidden behind feature flag so we don't have to support using a ChakraButton.
> [ENG-1600] feat: support reinstall integration

- src/components/Configure/content/fields/WriteFields/WriteFields.tsx
- src/components/Configure/content/fields/WriteFields/WriteFieldsV2.tsx
removes chakra and adds bridge component and native checkboxes to WriteFields
- add native checkboxes
> [ENG-1582] feat/refactor: remove chakra from WriteFields component

- src/components/Configure/content/CreateInstallation.tsx
- src/components/Configure/content/UpdateInstallation.tsx
- src/components/Configure/content/useMutateInstallation.tsx
- src/components/Configure/content/useSelectedConfigureState.tsx
- src/components/Configure/nav/ObjectManagementNav/ObjectManagementNavContext.tsx
- src/components/Configure/nav/ObjectManagementNav/index.tsx
There is currently no onboarding flow in the InstallIntegration component. When the user installs their integration with the first object, we do not show the user what to do next. This feature will navigate the user to the first uncompleted tab.
Picks first uncompleted tab
> [ENG-1601] feat: add on next tab ux to ObjectManagementNav

- src/components/Configure/InstallIntegration.tsx
- src/components/Configure/content/fields/FieldMappings/RequiredFieldMappings.tsx
- src/context/InstallIntegrationContextProvider.tsx
Adds dynamic fieldMapping prop to `InstallIntegration` component so builders can add dynamic field mappings per consumer. 
Tested it manually with `demo-hubspot-apollo-app`: https://github.com/amp-labs/demo-hubspot-apollo/pull/1 
How the mapping UI looks like when both static & dynamic fieldMappings are present: 
How the mapping UI looks like when both static & dynamic fieldMappings have to map the same field: 
Tested saving the configuration as well:
> [ENG-1602] feat: add `fieldMapping` prop to `InstallIntegration` component

- src/components/Configure/InstallIntegration.tsx
- src/components/Configure/content/fields/FieldMappings/FieldMapping.tsx
- src/context/InstallIntegrationContextProvider.tsx
- src/public/index.ts
1. Renames `fieldMappingType` to `fieldMapping`
2. Adds a public export of this type
3. Ensures combobox is pre-filled without chakra
4. Ensures options are loaded on load and not just while typing
Demo video: https://www.loom.com/share/36793eac1ea642659ea47ab548eeaeb0
> [ENG-1620] feat: rename field mapping type & add public export

- src/components/Configure/content/fields/FieldMappings/RequiredFieldMappings.tsx
- src/components/ui-base/ComboBox/ComboBox.tsx
Not totally sure why combobox breaks only on dynamic fields. It might have to do with items being re-rendered and the internal state is not catching the re-render. This PR adds a useEffect to explicitly listen to item changes. 
Navigate to an object that is not completed and supports dynamic fields. (see linear ticket for setup)
> [ENG-1620] fix: adds re-render state to combobox items

- src/components/Configure/nav/ObjectManagementNav/OtherTab.tsx
- src/components/Configure/nav/ObjectManagementNav/v2/Tabs/index.tsx
- src/components/Configure/nav/ObjectManagementNav/v2/index.tsx
Add other write tab to the v2 Tabs/ObjectManagementNav
- deprecates previous otherTab
- followup to https://github.com/amp-labs/react/pull/622
> [ENG-1629] feat/refactor: add other/write tab to ObjectManagementNav v2

- src/components/Configure/content/ConfigureInstallationBase.tsx
- src/components/Configure/nav/ObjectManagementNav/index.tsx
- src/components/Configure/nav/ObjectManagementNav/v2/Tabs/index.tsx
- src/components/Configure/nav/ObjectManagementNav/v2/Tabs/tabs.module.css
- src/components/Configure/nav/ObjectManagementNav/v2/index.tsx
supports uninstall tab without chakra. 
- adds ObjectManagementNav v2 under feature flag
- bases styling to danger button variant.
> [ENG-1585] feat/refactor: adds uninstall tab to ObjectManagementNav v2

- package.json
- src/assets/TooltipIcon.tsx
- src/components/Configure/content/fields/FieldMappings/FieldMapping.tsx
- src/components/Configure/content/fields/FieldMappings/RequiredFieldMappings.tsx
- src/components/ui-base/Tooltip/index.tsx
- yarn.lock
Makes Field Mappings more condensed. Currently field prompts take a lot of screen real estate, we move into tool tip. Less space and padding is preferred since consumers expect to have 20+ mappings. 
- adds react-tooltip dependency
- modifies field mapping padding
- adds tooltip component
> [ENG-1631] feat: add tooltip to field mappings

- src/components/Configure/content/fields/FieldMappings/RequiredFieldMappings.tsx
- src/components/form/FormControl/formControl.module.css
- src/components/form/FormControl/index.tsx
refactors RequiredFieldMappings to use native form control component
- add native form control to replace Chakra's
- adds error message to form control when not valid input is passed.
1. comment out form FieldMapping so default is not auto set.
```
//  setFieldMapping(selectedObjectName, setConfigureState, field.mapToName, field._default);
```
2. Install without selecting a RequiredFieldMapping
> [ENG-1580, ENG-1612] feat/refactor: add form control component

- src/components/Configure/layout/ConditionalProxyLayout/ConditionalProxyLayout.tsx
This PR helps debug rendering issue with uninstalling a Proxy.
The data flow is a little confusing. To debug, we'll need to look at the `InstallIntegration` component. 
```js
// InstallIntegration.tsx
<InstallIntegrationProvider > 
<ConnectionsProvider>
<ProtectedConnectionLayout>
<HydratedRevisionProvider>
<ConditionalProxyLayout > // router to switch component to the proxy component. see layout folder.
<ConfigurationProvider> // manages anything with the config object
<ObjectManagementNav> // left hand nav
<InstallationContent /> // right side content inside nav
</ObjectManagementNav>
</ConfigurationProvider>
</ConditionalProxyLayout>
</HydratedRevisionProvider>
</ProtectedConnectionLayout>
</ConnectionsProvider>
</InstallIntegrationProvider>
```
The re-render happens because …
> fix: rendering issue in ConditionalProxyLayout

- src/components/Configure/content/fields/FieldMappings/RequiredFieldMappings.tsx
Required field mappings was returning an empty array if fieldMappings didn't exists. We update the code to remove this line (fix), and to separate extracting required map fields and dynamic field mappings to be easier to read and maintain.
> fix: field mappings for required fields

- src/components/Configure/content/ConfigureInstallationBase.tsx
- src/components/Configure/content/fields/FieldHeader.tsx
- src/components/Configure/content/fields/OptionalFields/optionalFields.module.css
- src/components/Configure/content/fields/RequiredFields.tsx
- src/components/Configure/nav/ObjectManagementNav/index.tsx
- src/components/Configure/nav/ObjectManagementNav/v2/Tabs/tabs.module.css
- src/components/Configure/nav/ObjectManagementNav/v2/index.tsx
- src/components/SuccessTextBox/SuccessTextBox.tsx
- src/components/form/FormControl/formControl.module.css
- src/components/ui-base/Box/box.module.css
- src/components/ui-base/Button/button.module.css
- src/components/ui-base/Checkbox/checkbox.module.css
- src/components/ui-base/ComboBox/combobox.module.css
- src/styles/variables.css
This PR updates the styles for the native migrated components. 
- update spacing, borders in boxes, headers, and inputs
- rm box shadows
- update tab styles
- adjust checkbox sizing and spacing
- change background to white
**clean up variable.css**
- remove secondary background color
- remove unused colors
> [ENG-1657] style: update css default styles, simplify css variables

- src/components/ThemeProvider/Button/buttonTheme.ts
fix uninstall button by renaming to be danger variant.
> fix: rename warning to danger variant

- src/components/Configure/content/ConfigureInstallationBase.tsx
- src/components/Configure/content/fields/ObjectMapping.tsx
- src/components/Configure/content/fields/ReadFields.tsx
adds support for conveying when an object is mapped to builder's custom object.
update nav to support displayName and mapped display names https://github.com/amp-labs/react/pull/695
> [ENG-1650] feat: add read object mapping callout component

- src/components/Configure/nav/ObjectManagementNav/OtherTab.tsx
- src/components/Configure/nav/ObjectManagementNav/index.tsx
- src/components/Configure/nav/ObjectManagementNav/v2/Tabs/index.tsx
- src/components/Configure/types.ts
- src/components/Configure/utils.ts
followup to object mappings
- adds mapToDisplayName support in nav
- capitalize object name in nav if no displayName / mapToDisplayName is provided
Account (displayName) and People (mappedToDisplay)
followup to https://github.com/amp-labs/react/pull/692
> [ENG-1650] feat: add displayName to object management nav

- .github/workflows/npm-publish.yml
This will allow us to release non-stable versions of the react library such as `beta`, `rc-1`, `alpha` or `next`. These versions will be visible on npm  but not downloaded when someone installs the lib via `npm i @amp-labs/react` by default. 
They would have to explicitly install it via `npm i @amp-labs/react@alpha-1.0.0`
The value of the tag will be `latest` by default unless specificied, which will be the versions that show up on npm registry publicly and downloaded by default. 
Ref: https://docs.npmjs.com/cli/v10/commands/npm-dist-tag#purpose
> feat(dx): add ability to tag a release

- src/components/Configure/content/fields/FieldMappings/FieldMapping.tsx
- src/components/Configure/content/fields/ObjectMapping.tsx
- src/components/Configure/nav/ObjectManagementNav/v2/index.tsx
- src/components/Configure/resetCss.module.css
- src/components/auth/Oauth/AuthorizationCode/WorkspaceEntry/Salesforce/SalesforceSubdomainEntry.tsx
- src/components/ui-base/Button/button.module.css
- src/components/ui-base/Checkbox/checkbox.module.css
- src/components/ui-base/ComboBox/ComboBox.tsx
- src/components/ui-base/ComboBox/combobox.module.css
- src/components/ui-base/Divider/divider.module.css
- src/styles/variables.css
With Chakra removed, many styles are broken with padding no longer consistent. We remove padding/margin in out components in our css reset. We also make changes to 
- combobox
- checkbox
- buttons 
- divider 
- Salesforce Domain Entry
> [ENG-1677] style: update styles, reset with Chakra removed.

- src/components/Configure/utils.ts
The typeguard was checking for `mapToName`, which no longer works since IntegrationFieldExistent can also have `mapToName` now, checking for the existence of `fieldName` is more accurate. This PR also means the builders can start using builder-defined field mappings (they'll just look the same as regular required fields for now, which is fine). 
This is the test yaml file: https://github.com/amp-labs/testdata/blob/main/salesforce/amp.yaml#L9
This is what the UI library looks like:
- Billing city is a builder defined mapped field (shows up just like other required fields)
- Country is a consumer defined mapped field (shows dropdown to ask consumer to do maping)
This tab shows that if there were only consumer-field mappings, it still works:
> Fix: typeguard for isIntegrationMapping

- src/components/Configure/content/ConfigureInstallationBase.tsx
- src/components/Configure/content/fields/FieldHeader.tsx
- src/components/Configure/content/fields/FieldMappings/RequiredFieldMappings.tsx
- src/components/Configure/content/fields/OptionalFields/optionalFields.module.css
- src/components/Configure/nav/ObjectManagementNav/v2/Tabs/tabs.module.css
- src/components/Configure/nav/ObjectManagementNav/v2/index.tsx
- src/components/Configure/resetCss.module.css
- src/components/Docs/DocsHelperText.tsx
- src/components/ErrorTextBox/errorTextBox.module.css
- src/components/FormCalloutBox.tsx
- src/components/FormErrorBox.tsx
- src/components/Loading/style.module.css
- src/components/form/FormControl/formControl.module.css
- src/components/form/Input/input.module.css
- src/components/form/Textarea/textarea.module.css
- src/components/ui-base/Button/button.module.css
- src/components/ui-base/Checkbox/checkbox.module.css
- src/components/ui-base/ComboBox/combobox.module.css
- src/components/ui-base/Tag/index.tsx
- src/styles/variables.css
This PR syncs up designs closer to mocks and converts global variables to use semantic variables from our [ui pallete](https://www.figma.com/design/sBbeJCAqMVaH8vYZpXwWBC/Simple-UI-For-Ampersand?node-id=1-2&node-type=canvas&t=vNbrLHpYyUFs5Vvr-0). 
- match design system variables to UI Pallette
- remove computed doc styles (temporary bridge from migration)
- update button styles
- update neutral colors to match UI Pallette
- make combobox menu items smaller
- make combobox input same size as label
- exposes font-family as a override css variable
- addresses [ENG-1680, ENG-1682]
> [ENG-1689] styles: update design system variables and layout

- src/layout/AuthCardLayout/AmpersandFooter.tsx
> style: add dark mode to footer

- generated-sources/api/src/apis/ConnectionApi.ts
- generated-sources/api/src/models/AuthType.ts
- src/components/Configure/InstallIntegration.tsx
- src/components/Configure/layout/ProtectedConnectionLayout.tsx
- src/components/Connect/ConnectProvider.tsx
- src/components/Connect/ConnectedSuccessBox.tsx
- src/components/Connect/RemoveConnectionButton.tsx
- src/components/Connect/useConnectionHandler.tsx
- src/context/ConnectionsContextProvider.tsx
- src/hooks/useForceUpdate.tsx
1. Adds remove connection after successful connect with ConnectProvider
2. Adds a deprecation flag to onSuccess in favor of onConnectSuccess
3. Adds onDisconnectSuccess callback
> [ENG-1725] feat: add remove connection button

- src/components/Configure/content/ConfigureInstallationBase.tsx
- src/components/Configure/content/CreateInstallation.tsx
- src/components/Configure/content/UpdateInstallation.tsx
- src/components/Configure/nav/ObjectManagementNav/constant.tsx
- src/components/Configure/nav/ObjectManagementNav/v2/Tabs/index.tsx
- src/components/Configure/nav/ObjectManagementNav/v2/index.tsx
- src/components/Configure/state/ConfigurationStateProvider.tsx
- src/components/Configure/utils.ts
- src/components/auth/Oauth/AuthorizationCode/fetchOAuthPopupURL.ts
Users have found the "Other" tab to be confusingly named.
> feat: Rename other tab to write

- src/components/Configure/InstallIntegration.tsx
- src/context/ConnectionsContextProvider.tsx
- src/context/IntegrationListContextProvider.tsx
- src/context/ProjectContextProvider.tsx
Part 1 of moving loading away from Ampersand Provider
- moved loading down from AmpersandProvider
- move project and integrationList loading to InstallIntegration
- move project loading to ConnectProvider
> refactor: move project loading to Install Integration

- src/components/Configure/layout/ProtectedConnectionLayout.tsx
- src/components/Connect/ConnectProvider.tsx
- src/components/Connect/ConnectedSuccessBox.tsx
- src/components/Connect/RemoveConnectionButton.tsx
- src/components/Connect/useConnectionHandler.tsx
- src/public/index.ts
I realized that only triggering the onConnectSuccess and onDisconnectSuccess callbacks with the Connection ID is not particularly useful. (For example, a customer wants to be able to customer data cleanup in the onDisconnectSuccess callback, so they'll need to know things like groupRef).
Since these 2 callbacks have not been released yet, it's a good time to change their signature. This video shows the new callbacks working, and that the legacy `onSuccess` callback still works:
https://www.loom.com/share/5438ea6be29d4ef69d5c6971f7c69a11?sid=6adf1832-0e77-496e-9cdb-7a28697d4058
Here's a dump of the Connection that the callback receives, it's the version of the Connection that does not have any sensitive info (no tokens). 
```
{
"id": "965126de-05b5-419d-b9a0-4391c77cf03b",
"projectId": …
```
> change signature of onConnectSuccess and onDisconnectSuccess

- src/components/Configure/ComponentContainer.tsx
- src/components/Configure/InstallIntegration.tsx
- src/components/Configure/layout/ConditionalProxyLayout/ConditionalProxyLayout.tsx
- src/components/Configure/state/HydratedRevisionContext.tsx
- src/context/ConnectionsContextProvider.tsx
- src/context/InstallIntegrationContextProvider.tsx
- src/context/IntegrationListContextProvider.tsx
- src/context/ProjectContextProvider.tsx
[previous work](https://github.com/amp-labs/react/pull/747) moved loading outside of Ampersand Provider, we will need to move the error ui so that UI problems at the top level do not occur for the builder
- move error ui to InstallIntegration
- move error ui to ConnectProvider
- create ComponentContainer to wrap outer layer and error components
- swap out `<LoadingCentered/>` and `<ErrorTextBox/>` to include a Component Border (`<ComponentContainerLoading/>`, `<ComponentContainerError/>` )
> [ENG-1720] fix/refactor: move error ui out of Ampersand Provider

- src/components/Configure/content/fields/OptionalFields/optionalFields.module.css
- src/components/form/Input/input.module.css
- src/components/form/Textarea/textarea.module.css
- src/components/ui-base/Button/button.module.css
- src/components/ui-base/Checkbox/checkbox.module.css
- src/components/ui-base/ComboBox/combobox.module.css
- src/styles/variables.css
Adds additional semantic variables for specific input css color control. Preps variables for dark mode. 
- fixes input css bug with input border radius
- removes default outline in input
followup part 2: https://github.com/amp-labs/react/pull/756
note: this may introduce breaking changes with css variable name change @laurenzlong 
css changes are minor
input outline can border radius fix
> [ENG-1709] style: update input semantic variables

- src/assets/TrashIcon.tsx
- src/components/Configure/nav/ObjectManagementNav/v2/Tabs/tabs.module.css
- src/components/ui-base/Button/button.module.css
- src/styles/variables.css
To support dark mode the user must create their own style override if not already turned on in the app 
- adds dark mode to semantic variables
part 1: https://github.com/amp-labs/react/pull/755
```css
// your style overrides App.css, imported after stylesheet
:root {
color-scheme: light dark;
}
```
- trash icon / tab red color change
> [ENG-1709] style: add dark mode light-dark palette (part 2)

- src/context/ProjectContextProvider.tsx
- src/services/api.ts
- create a useAPI hook like in the client
- refactor `project` api call to use new service
- migrating all instances of api 
- setting / overriding api key service instance
> [ENG-1670] refactor: move api key to API service config

- src/components/Configure/content/fields/FieldMappings/OptionalFieldMappings.tsx
- src/components/Configure/content/fields/FieldMappings/RequiredFieldMappings.tsx
- src/components/Configure/content/fields/FieldMappings/index.ts
- src/components/Configure/content/fields/ReadFields.tsx
- src/components/Configure/layout/ConditionalProxyLayout/ConditionalProxyLayout.tsx
- src/components/Configure/state/utils.ts
- src/components/Configure/types.ts
- src/components/Configure/utils.ts
Supports optional field mappings
- creates a separate section for optional field mappings
- with `lead` object -- hydrated revision error
- with dynamic field mappings
further testing maybe necessary 
- test optional only
> [ENG-1758]feat: support OptionalFieldMappings

- src/layout/AuthCardLayout/AmpersandFooter.tsx
Replace previous logo URL with cloudinary URL, since cloudinary sets CORS headers properly which will help us avoid having some builders not being able to render the logo in their app (see Linear ticket for screenshot of bug)
This PR also makes use of the `picture` element to conditionally render the right logo for light and dark mode, picture element seems to supported by all major browsers: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture
> [ENG-1757] fix: logo rendering issues and use the correct logo for light/dark mode

- src/components/Configure/layout/ConditionalProxyLayout/ConditionalProxyLayout.tsx
Reinstall proxy flow is triggered automatically after deleting proxy integration. Part 1:
- if integration is deleted, do not retrigger create flow if integration is deleted.
- does not persist when refreshed (followup below)
See https://linear.app/ampersand/issue/ENG-1780/bug-uninstall-proxy-reinstalls-automatically for root issue in uninstall flow.
if page is refreshed, the create proxy integration flow will still re-trigger since  a connection is still available and triggers after detecting connection. will still need
> [ENG-1780] fix: uninstall / reinstall proxy flow (part 1)

- src/components/Configure/InstallIntegration.tsx
- src/components/Configure/layout/ConditionalProxyLayout/ConditionalProxyLayout.tsx
- src/components/Configure/layout/ProtectedConnectionLayout.tsx
- src/components/Configure/layout/UninstallButton.tsx
- src/context/ConnectionsContextProvider.tsx
Part 2 rewrite based on feedback from https://github.com/amp-labs/react/pull/786
The uninstall flow will now be connection dependent. 
- delete connection when installation is deleted
- move reinstall layout to connections level
- migrate connections api to use new api service hook
> [ENG-1780] fix: reinstall proxy flow connections (part 2b)

- src/components/Configure/content/fields/FieldDefaultValueMapping/FieldDefaultValueMapping.tsx
- src/components/Configure/content/fields/WriteFields/WriteFields.tsx
adds placeholder ui for default value mapping
- sets internal feature flag `DEFAULT_VALUE_FF`
followup: https://github.com/amp-labs/react/pull/808
> feat: add ff for default value mapping

- src/components/Configure/content/fields/FieldDefaultValueMapping/FieldDefaultValueMapping.tsx
- src/components/Configure/content/fields/FieldDefaultValueMapping/FieldDefaultValueTable.tsx
- src/components/Configure/content/fields/FieldDefaultValueMapping/NewDefaultValueUI.tsx
- src/components/ui-base/ComboBox/ComboBox.tsx
creates a new component to add FieldValueDefaults. The change does not update the objectConfiguration state yet and is just a localized component. 
- adds FieldDefaultValueTable component
- adds FieldDefaultValueMapping component
- style: update default value mapping ui styling
- refactor: move new default value UI to separate component
note: this feature is behind an internal FF `DEFAULT_VALUE_FF`
Connect to objectConfiguration state and add save to server functionality.
> [ENG-1784] feat: adds field default ui builder

- generated-sources/api/src/models/HydratedIntegrationObject.ts
- src/components/Configure/InstallIntegration.tsx
- src/components/Configure/actions/read/onSaveReadCreateInstallation.ts
- src/components/Configure/actions/read/onSaveReadUpdateInstallation.ts
- src/components/Configure/content/ConfigureInstallationBase.tsx
- src/components/Configure/content/fields/FieldMappings/RequiredFieldMappings.tsx
- src/components/Configure/content/fields/FieldMappings/ValueMappingItem.tsx
- src/components/Configure/content/fields/FieldMappings/ValuesFieldMapping.tsx
- src/components/Configure/content/fields/FieldMappings/ValuesMapping.tsx
- src/components/Configure/content/fields/FieldMappings/index.ts
- src/components/Configure/content/fields/FieldMappings/setValueMapping.ts
- src/components/Configure/content/fields/ReadFields.tsx
- src/components/Configure/nav/ObjectManagementNav/v2/Tabs/index.tsx
- src/components/Configure/state/ConfigurationStateProvider.tsx
- src/components/Configure/state/utils.ts
- src/components/Configure/types.ts
- src/components/Connect/ConnectProvider.tsx
Adds a way to add value mappings alongside other mappings
Tested with the following fieldMapping configuration on `InstallIntegration` component
Successfully updates / creates the `selectedValueMapping` in the config from the UI 
**Follow up PRs:** 
1. To fix glitch on the ComboBox selector
2. Better error handling & messages (currently on console.error)
> [ENG-1768] feat: values mapping (phase1a)

- src/components/Configure/content/fields/FieldMappings/FieldMapping.tsx
- src/components/Configure/content/fields/FieldMappings/OptionalFieldMappings.tsx
- src/components/Configure/content/fields/FieldMappings/RequiredFieldMappings.tsx
- src/components/Configure/content/fields/FieldMappings/setFieldMapping.ts
This PR fixes the field mapping bug where the field mapToName fed to `<InstallIntegration>` component changes, bug was introduced because previously selected mappings were not removed even thought it is removed from UI. 
This PR removes deprecated mappings that was present prior to code change to builders. 
- Before Update
- After Code Update and updating installation
> [ENG-1805] Bug: field mapping should not persist old mappings

- src/components/Configure/content/fields/ValueMapping/ValuesMapping.tsx
**This PR allows multiple fields per object to be saved with value mapping.**
**The "save" button only gets enabled when all the fields are fully mapped with values:**
> [ENG-1768] feat: allow multiple fields per object for value mapping

- src/components/Configure/actions/write/generateConfigWriteObjects.ts
- src/components/Configure/content/fields/WriteFields/WriteFieldsV2.tsx
- src/components/Configure/content/fields/WriteFields/setNonConfigurableWriteField.tsx
- src/components/Configure/state/utils.ts
- src/components/Configure/types.ts
- src/services/api.ts
Simplify and prep the write draft state to allow tracking write access in both non-configure state and configure state (type includes default value field)
- remove old array transformation logic
- use config type when setting write objects in form
> [ENG-1784] refactor: write objects state in configurationState

- src/components/Configure/content/fields/FieldDefaultValueMapping/FieldDefaultValueMapping.tsx
- src/components/Configure/content/fields/FieldDefaultValueMapping/FieldDefaultValueTable.tsx
- src/components/Configure/content/fields/FieldDefaultValueMapping/NewDefaultValueUI.tsx
- src/components/Configure/content/fields/FieldDefaultValueMapping/setValueDefaultWriteField.tsx
- add "add" ability for default value write field state
- add "delete" ability for default value write field state
- adds setValueDefaultWriteField producer to modify state (using immer)
- supports showing/hiding default value mapping section only when write access is selected.
- save / modify functionality 
note: This feature is still behind feature flag `DEFAULT_VALUE_FF `. You will need to manually set this in the code to turn this on.
Add display name support to fields for default value (needs to fetch from hydrated revision)
> [ENG-1784] feat: add state management for value default write

- src/components/Configure/content/fields/FieldDefaultValueMapping/FieldDefaultValueTable.tsx
- src/components/Configure/content/fields/FieldDefaultValueMapping/NewDefaultValueUI.tsx
- src/components/Configure/state/HydratedRevisionContext.tsx
This PR adds the default value displayname looked up via the hydratedRevision.
- adds readAction into hydratedRevision context
Displayname "Account Currency" is pulled correctly.
> [ENG-1784] feat: adds displayName lookup to field default value list

- src/components/Configure/content/fields/FieldDefaultValueMapping/FieldDefaultValueMapping.tsx
- src/components/Configure/state/HydratedRevisionContext.tsx
checks hydratedRevision if default values are allowed
- moves write objects to hydrated revision 
note: this feature is hidden behind internal feature flag`DEFAULT_VALUE_FF`
resolved: ~https://ampersand-company.slack.com/archives/D059B9LTELS/p1737140314929909~
> [ENG-1784] feat: checks hydratedRevision if default values are allowed

- src/components/Configure/content/fields/FieldMappings/FieldMapping.tsx
adds ability for user to clear or reset the set field mapping.
- will reset to default if available
- will remove the field mapping if no default
resets to default when available
> [ENG-1764] feat: add 'clear' button on field mappings

- src/components/Configure/content/fields/FieldMappings/FieldMapping.tsx
- src/components/Configure/content/fields/FieldMappings/RequiredFieldMappings.tsx
Optional field mappings were broken. 
- fixes outdated keys to include checking optional fields
**root cause**: broken field mappings occur when the amp.yaml spec or dynamic fields are updated yet the field still exists in the config. There is a filter that checks dynamic and required fields. Optional fields were not checked in the filter so the optional fields were always set to null. 
Logic living in required field mappings made difficult to debug for broken optional fields. 
**followup:** Refactor outdated keys logic to be easier to find. Unset logic currently renders every time config is updated in the required fields directory affecting optional state.
> [ENG-1818] fix: optional field mappings

- src/components/Configure/content/fields/FieldMappings/RequiredFieldMappings.tsx
- src/components/Configure/content/fields/FieldMappings/useClearOldFieldMappings.tsx
- src/components/Configure/content/fields/ReadFields.tsx
followup to fixing optional field mappings. https://github.com/amp-labs/react/pull/831
- moves logic from RequiredFieldMappings to useClearOldFieldMappings hook
- updates ReadFields to use hook
optional field mappings works as expected
> [ENG-1818] refactor: clear old field mappings

- src/components/Configure/content/UpdateInstallation.tsx
- pending state resets when install / save button is clicked. 
- whenever tab switched the pending state will also reset. 
remove the `useEffect` reset that tracks `installations` / config changes. 
`installations` is updated after install (updating config), which we do not want to call a reset state which also wipes pending draft states. Additionally if we track reset state in any useEffect dependencies, the reset will also activate whenever the tab `selectedObjectName` switches which causes undesirable resets.
> [ENG-1798] fix: allow pending states to persist

- package.json
- src/context/AmpersandContextProvider/AmpersandContextProvider.tsx
- src/context/ProjectContextProvider.tsx
- yarn.lock
Adds react-query.
imported amp-labs/react into dashboard. tested that this branch work: 
1. in current dashboard (same react-query version) 
2. dashboard with down graded react-query (v. 4.3)
To test locally 
1. Compile react lib into a tar ``` tar --exclude='node_modules' --exclude='.git' -vczf amp-react-rq.tgz .```
2. Install tar package locally in client ```npm i ../react/amp-react-rq.tgz ```
- Manages fetching, caching, requests through policies and smart defaults. 
- Also ships with significant dev tooling that allows debugging by overriding fetching, loading, error state per requests. 
- Simplify our fetching logic in place of home rolled useEffect based fetching. 
- Less code. Easier to maintain. Consistent with dashboard codebase. 
- Untested - what happens if there are …
> [ENG-1837] build: add tanstack query

- src/components/Configure/content/fields/FieldMappings/OptionalFieldMappings.tsx
0 is rendered with dynamicFieldMappings is length 0.
> fix: empty dynamic optional field mappings 

- src/components/Configure/InstallIntegration.tsx
- src/components/Configure/state/HydratedRevisionContext.tsx
- src/context/ConnectionsContextProvider.tsx
We add react query to simplify how to manage syncing connections. This is prep work for [ENG-1778] bug. Simplifying logic in connections manager via react query helps avoid re-render issues when switching connections
- simplify connections context
- derive connection from connections list
- remove manual set connections/ connection
- adds loading state to hydrated revision which previously showed an error when connection was set.
1. useEffect, deps, prop changes, and actions from user (auth) trigger a re-fetch of listConnections
2. based on oauth and connections, we use a useEffect connections manager to set the selected connection and keep them in sync
issues: syncing selectedConnection and connections can create a endless cycle has they trigger multiple useEffects to update each other …
> [ENG-1778, ENG-1837] refactor: connections to use react query (connections part 1) 

- src/components/Configure/InstallIntegration.tsx
- src/components/Configure/content/ConfigureInstallationBase.tsx
- src/components/Configure/content/InstallationContent.tsx
- src/components/Configure/content/UninstallContent.tsx
- src/components/Configure/content/fields/FieldMappings/OptionalFieldMappings.tsx
- src/components/Configure/content/fields/FieldMappings/useClearOldFieldMappings.tsx
- src/components/Configure/content/fields/ObjectMapping.tsx
- src/components/Configure/content/fields/ValueMapping/ValuesMapping.tsx
- src/components/Configure/content/useMutateInstallation.tsx
- src/components/Configure/layout/ConditionalProxyLayout/ConditionalProxyLayout.tsx
- src/components/Configure/layout/ProtectedConnectionLayout.tsx
- src/components/Configure/layout/UninstallButton.tsx
- src/components/Configure/nav/ObjectManagementNav/v2/index.tsx
- src/components/Configure/state/ConfigurationStateProvider.tsx
- src/components/Configure/state/HydratedRevisionContext.tsx
- src/context/ConnectionsContextProvider.tsx
- src/context/InstallIIntegrationContextProvider/InstallIntegrationContextProvider.tsx
- src/context/InstallIIntegrationContextProvider/useIsInstallationDeleted.ts
Problem: when InstallIntegration is passed in different props, the isIntegrationDeleted state stays the same. The useIsIntegrationDeleted hook was not a global context.
Solution: reset the integrationDeleted state when props change. 
- resets the isIntegrationDeleted state when InstallIntegration props change
- refactors useIsInstallationDeleted hook inside InstallIntegrationContextProvider
- updates import paths
- deletes files being moved
1. Setup props in mailmonkey to switch between hubspot and salesforce
2. Authenticate hubspot proxy - see success screen
3. Switch to Salesforce 
4. Switch back to hubspot - uninstall - see uninstall screen
5. Switch back to Saleforce and back to Hubspot
6. Hubspot should now have restarted flow.
> [ENG-1778] fix/refactor: isIntegrationDeleted during prop change

- src/components/Connect/ConnectProvider.tsx
- src/context/InstallIIntegrationContextProvider/InstallIntegrationContextProvider.tsx
- src/hooks/query/useListInstallationsQuery.ts
adds react query to installations
- adds react query in place of useEffect triggered installations
- does not include migration for installation mutations.
- installations logic is now always derived from list installations. (no need to manually set installation)
needed to fix https://github.com/amp-labs/react/pull/862
> [ENG-1837] refactor: add react query to installations

- src/components/Configure/InstallIntegration.tsx
- src/components/Configure/layout/ConditionalProxyLayout/ConditionalProxyLayout.tsx
- src/components/Configure/layout/ProtectedConnectionLayout.tsx
- src/components/Configure/state/HydratedRevisionContext.tsx
- src/context/AmpersandContextProvider/AmpersandContextProvider.tsx
- src/context/ConnectionsContextProvider.tsx
- src/context/InstallIIntegrationContextProvider/InstallIntegrationContextProvider.tsx
- src/context/IntegrationListContextProvider.tsx
- src/hooks/query/useListInstallationsQuery.ts
- src/hooks/useIsIntegrationInstalled.ts
the `useIsIntegrationInstalled` hook is out of sync from the installations query. After refactoring list installations to use react query, 
- add in some cache invalidation logic to enable the hook state to be synced. 
- fixes some unnecessary fetches
followup to https://github.com/amp-labs/react/pull/844
integration installed hook tested in mailmonkey
> [ENG-1910] fix: useIsIntegrationInstalled 

- src/components/Configure/state/HydratedRevisionContext.tsx
- src/context/ConnectionsContextProvider.tsx
add a little bit of margin to the hydrated revision logic, since we're running into possible errors with connection id not ready yet.
- adds retries to hydrated revision
- adds retries to connections before showing error
longer term solution would migrate the create connections logic to use react query, simplifying connections logic more and revisit issue.
> chore: increase query retries for hydrated revision

- src/utils/handleServerError.ts
Errors are not able to be read from the response more than once. 
1. We create a clone that will attempt to read instead of creating an unhandled error.
2. Surround with try/catch to prevent unhandled errors
> fix: add error handling try/catch

- src/components/auth/BasicAuth/BasicAuthFlow.tsx
- src/components/auth/NoAuth/NoAuthFlow.tsx
- src/components/auth/useCreateConnectionMutation.ts
Refactors basic auth flow to use a react-query mutation. 
- removes cred unnecessary form state <useState>
- migrates api service
- removes useEffect
merges in refactor no auth
- only used in testing. 
followup: https://github.com/amp-labs/react/pull/871
> [ENG-1837] refactor: basic auth flow to use react-query

- src/components/auth/ApiKeyAuth/ApiKeyAuthFlow.tsx
continue refactoring generate connections in API key flow
- use react-query for api key flow
- remove useState and useEffect
followup to: https://github.com/amp-labs/react/pull/869
> [ENG-1837] refactor: api key flow

- src/components/Configure/InstallIntegration.tsx
- src/components/Configure/content/fields/FieldMappings/DynamicFieldMappings.tsx
- src/components/Configure/content/fields/FieldMappings/FieldMappingRow.tsx
- src/components/Configure/content/fields/FieldMappings/OptionalFieldMappings.tsx
- src/components/Configure/content/fields/FieldMappings/RequiredFieldMappings.tsx
- src/components/Configure/content/fields/FieldMappings/index.ts
- src/public/index.ts
Looks like the export broke at some point, and we were accidentally exporting the React component named FieldMapping and not the type. This PR rename the React component to FieldMappingRow to differentiate it from the FieldMapping type (which is a prop of InstallIntegration), and also updated the docstrings to make them more builder-friendly.
> fix: FieldMapping type export

- src/components/Configure/content/fields/ObjectMapping.tsx
- src/components/Configure/layout/ConditionalProxyLayout/InstalledSuccessBox.tsx
- src/components/Configure/layout/ProtectedConnectionLayout.tsx
- src/components/Configure/nav/ObjectManagementNav/v2/index.tsx
- src/components/Connect/ConnectedSuccessBox.tsx
- src/components/auth/ApiKeyAuth/ApiKeyAuthContent.tsx
- src/components/auth/BasicAuth/BasicAuthContent.tsx
- src/components/auth/Oauth/OauthFlow/OauthFlow.tsx
- src/hooks/useProvider.tsx
- src/utils/index.ts
Sometimes provider displayName does not show correctly. We move the util function inside a new hook `useProvider` which extends the providerInfoQuery with derived state.
- adds useProvider hook
- enforce providerInfo as when getting the displayname
> [ENG-1920] fix: provider display name

- src/components/Configure/nav/ObjectManagementNav/v2/index.tsx
- src/components/ui-base/ComboBox/ComboBox.tsx
- src/components/ui-base/ComboBox/combobox.module.css
- adds styling for top menu
- adjust padding for allowing space for bottom menu
- reduces combobox menu length
> style: adjust padding and size of combobox

- src/components/Configure/content/fields/ValueMapping/ValuesMapping.tsx
Console is flooded with error logging from checking if fields are valid ValueMappings...Please clarify if we need these. I've removed these to prevent our console errors from blowing up.
> fix: value mapping errors

- src/components/Connect/ConnectProvider.tsx
- src/context/ConnectionsContextProvider.tsx
`<ConnectProvider/>` was infinite loading. `<ConnectProvider/>` uses components coupled to InstallIntegration (uses installIntegration props).
- adds ability to pass in groupRef and provider to ConnectProvider
- overloads check to InstallIntegration hook
- remove connection button doesn't work. 
- should also consider decoupling <ConnectProvider/> and <InstallIntegration/> shared components.
listConnections call is now made (first row)
> [ENG-2026] fix: ConnectProvider list connections query

- src/components/Connect/RemoveConnectionButton.tsx
clean up delete connection button
- refactors to use new apiService and react-query mutation
> refactor: delete connection mutation

- .github/workflows/lint.yml
- package.json
**Explicit non-zero return in case of lint errors in CI:**
> [ENG-1966] fix: ensure github action fails in case of linter errors

- src/components/Configure/ComponentContainer.tsx
- src/components/Configure/InstallIntegration.tsx
- src/components/Configure/state/HydratedRevisionContext.tsx
- src/components/Connect/RemoveConnectionButton.tsx
- src/components/ErrorTextBox/ErrorTextBox.tsx
- src/utils/handleServerError.ts
Hydrated error state console logs error, but does not add detail to UI error. 
- adds UI causes error for hydrated revision
- adds disconnect button 
- adds disconnect error UI 
note demo does not show causes arrary in UI since hydrated revision error is triggered by react-query error; does not recreate hydrated revision error from our amperand server endpoint. similiar logic is used in the disconnect button however.
> [ENG-1980] feat: add hydrated revision error ui, disconnect button + error

- src/context/ProjectContextProvider.tsx
- src/hooks/query/useProjectWithEntitlementsQuery.ts
- src/layout/AuthCardLayout/AmpersandFooter.tsx
Creates a separate query for fetching projects with entitlements. 
Trade offs:
- fetches projects with entitlements only when Ampersand footer is rendered 
- double fetches project whenever footer is present 
notes: if performance is a concern than, we should consider entitlements as a separate endpoint.
> performance: useProjectWithEntitlementsQuery

- src/components/Configure/layout/ConditionalHasConfigurationLayout/ConditionalHasConfigurationLayout.tsx
- src/hooks/mutation/useCreateInstallationMutation.ts
followup to supporting proxy and subscribe create installation
- move create installation to a react-query mutation hook
- add support for subscribe-only installations
- refactor proxy-only installations to use the new mutation hook
> refactor: create installation mutation

- src/components/auth/Oauth/AuthorizationCode/NoWorkspaceEntry/NoWorkspaceOauthFlow.tsx
- src/components/auth/Oauth/AuthorizationCode/enableCSRFprotection.ts
- src/components/auth/Oauth/AuthorizationCode/fetchOAuthPopupURL.ts
- src/components/auth/Oauth/AuthorizationCode/useOAuthPopupURL.ts
- src/hooks/query/index.ts
- src/hooks/query/useListProviderAppsQuery.ts
- src/hooks/query/useOauthConnectQuery.ts
- src/hooks/useProvider.tsx
This PR refactors the OAuth flow by migrating from fetchOAuthPopupURL to a new hook, useOAuthPopupURL, and integrating react-query to manage API calls and error handling.
- migrate to useQuery
- add error handling
- add refetch function
- add useEffect to handle errors
- add useEffect to handle provider info
- add useEffect to handle provider apps
- add useEffect to handle oauth connect
does not migrate workspace oauth entries
part 2: https://github.com/amp-labs/react/pull/947
> [ENG-1837] refactor: move oauth flow to useOAuthPopupURL

- src/headless/InstallationProvider.tsx
Adds a provider for shared params to headless lib. 
- creates a new folder `headless`
- adds InstallationProvider
note: integrationId is specified rather than integration. I find it difficult to distinguish integrationId, integration(object), and integrationName. I change this to integrationId so we're not fetching the object to get the id. spec change may be required.
Consider renaming to HeadlessInstallationProvider.
> [ENG-2099] feat: [headless] adds InstallationProvider 

- src/headless/useConnections.ts
This PR adds useConnection hook. The hook returns the following: 
```
return {
connection, // first connection in connections array
error,
isLoading: isPending || isFetching,
isError,
isSuccess,
};
```
note: isLoading is overloaded with isPending (no data yet) and isFetching (query is fetching). Note that react-query does this to allow optimistic updates (you can have data and still be fetching), overriding with isLoading will take away this feature in exchange for simplicity.
> [ENG-2100]: [headless] useConnection 

- src/context/ConnectionsContextProvider.tsx
connections was not being detected.
root cause: group ref was missing (overloaded in a few components), easy to miss.
Oauth connections should work as expected.
- may need to consider adding oauth simple integration tests to make sure components load. 
- decouple headless and install components to use different hooks when context dependent.
> fix: connections not being detected

- src/components/form/Input/input.module.css
- src/components/ui-base/Button/button.module.css
address button feedback
- removes active selected state from basic button
- removes 2px outline from input to match
> [ENG-1974] style: remove button outline

- src/headless/manifest/useHydratedRevisionQuery.ts
- src/headless/manifest/useManifest.ts
adds a useManifest hook which will help get fields from the manifest (amp.yaml)
- add useHydratedRevisionQuery in headless
- add getters in manifest
note: the headless folder is not public in the repo.
When the getters fail, we return null to allow for more graceful rendering logic and the ability for the UI to handle not found cases. The builder may need to null-check.
We can test this inside the existing app by add an InstallationProvider at the InstallIntegration top level component and calling the use manifest hook along with destructuring inside a useEffect as follows:
```js
// InstallationContent will be wrapped by InstallationProvider
export function InstallationContent() {
const manifest = useManifest();
useEffect(() => {
const { getReadObject, getCustomerFieldsForObject, …
```
> [ENG-2101] feat: add useManifest hook

- src/hooks/query/index.ts
- src/hooks/query/useConnectionQuery.ts
Part 1 in Update Connection in InstallIntegration 
- adds useConnectionQuery in hooks/query folder
```js
import { useEffect } from 'react';
import { useConnectionQuery } from 'src/hooks/query';
export function UninstallContent() {
const { installation } = useInstallIntegrationProps();
const connectionId = installation?.connection?.id || '';
const { data: connection } = useConnectionQuery({ connectionId });
useEffect(() => {
if (connection) {
console.log('connection', connection);
}
}, [connection]);
return (
// smth
);
}
```
> feat: add useConnectionQuery hook

- src/components/auth/Oauth/AuthorizationCode/OAuthWindow/OAuthWindow.tsx
- src/components/auth/Oauth/AuthorizationCode/WorkspaceEntry/WorkspaceOauthFlow.tsx
fixes issue with oauth window re-opening even when user closes the window and there is an error 
checks if there is a successful connection or error before triggering openAuthWindow()
> [ENG-2154] fix: oauth infinite window loop

- src/components/Configure/content/manage/AuthenticationSection.tsx
- src/components/Configure/content/manage/updateConnection/UpdateConnectionSection.tsx
- src/components/Configure/content/manage/updateConnection/updateApiKeyConnect.tsx
- src/components/auth/ApiKeyAuth/ApiKeyAuthContent.tsx
- src/hooks/mutation/useUpdateConnectionMutation.ts
- refactor api key form 
- adds update api key connection form
- adds ghost variant for update connection form
- fixes authenticate section to find connection if installation is not available
tested using monday integration (prod, connector-test-project)
If the user tries to re-authenticate and no installation exists, the component will reset and change back to the first tab.
> [ENG-2149] feat/refactor: api key connection, update api keyconnection

- src/components/Configure/content/ConfigureInstallationBase.tsx
There is no need for the save and reset button on the manage tab. Removes when the tab is selected.
> feat: remove buttons save and reset on manage tab

- src/components/Configure/content/manage/AuthenticationSection.tsx
- src/components/Configure/content/manage/updateConnection/updateApiKeyConnect.tsx
- src/components/auth/ApiKeyAuth/ApiKeyAuthContent.tsx
clicking submit on the update connection flow was causing the app to reload and re-render. 
This bug is caused by an underlying implementation that nests the borrowed `AuthKeyAuthForm` submit button in the `ConfigureBase` save/create installation form. 
This PR does a quick fix and turns off the submit type button, however the bug shows a tech debt issue with the current tab structure.
- make submit button exception
- extra: removes extra calls to connection in the auth tab 
will need to also fix this in the other auth flows.
> fix: form submission/re-render issue

- src/components/Configure/content/manage/updateConnection/UpdateClientCredentialsConnect.tsx
- src/components/auth/Oauth/ClientCredentials/ClientCredentialsContainer.tsx
- src/components/auth/Oauth/ClientCredentials/ClientCredentialsContent.tsx
- src/components/auth/Oauth/ClientCredentials/ClientCredentialsCredsContent.tsx
update client credentials
- refactors client credentials form to use without border in the update connections flow
note: we'll waive end to end testing for this feat. will just show the UI as intended. (updateConnection endpoint works for apiKey)
To test the Update Connections tab, you'll need to switch the hard coded feature flag to: `SHOW_MANAGE_TAB = true`
1. Deploy Marketo Integration Amp.Yaml with some configuration
2. Setup Provider App and destination in console
3. InstallIntegration via mailmonkey/demo-app and use Marketo projectId and integrationName
4. Login with Client Credentials to Marketo
5. Click install after configuring.
6. Click on placeholder manage tab (may be hidden if SHOW_MANAGE_TAB is not turned on)
7. Fill out the client credentials in Update Connection section of …
> [ENG-2157] feat: update client credentials

- src/components/Configure/nav/ObjectManagementNav/v2/Tabs/index.tsx
- src/components/Configure/nav/ObjectManagementNav/v2/Tabs/showManageTabFF.ts
adds feature flags (vite, next, create react app)
change mailmonkey prod command: 
```json
"start:prod": "PORT=3003 REACT_APP_AMP_SERVER=prod REACT_APP_AMP_SHOW_MANAGE_TABS=true npm start",
```
> feat: add feature flag to show manage tabs

- package.json
allow builder projects to use app with react 19. currently being tested in preview
https://storage.googleapis.com/ampersand/react/amp-labs-react-19.tgz
> build: bump peer deps to allow React 19

- src/headless/installation/useInstallation.ts
useInstallation doesn't fetch since integration and group ref were not passed in. the params are optional for the InstallIntegration component but required for headless.
> fix: useInstallations query with integration name and group ref

- src/components/auth/Oauth/AuthorizationCode/NoWorkspaceEntry/NoWorkspaceOauthFlow.tsx
Hubspot integration has infinite window glitch. https://ampersand-company.slack.com/archives/C082KPRN4R4/p1746117116619159?thread_ts=1746117090.872019&cid=C082KPRN4R4
root cause: the issue lies only in noworkspace oauth flows
- pass in error to oauth window so that it does not re-open the window
- OAuthWindow will not open a window if an error is present.
> fix: no workspace oauth flow

- src/headless/InstallationProvider.tsx
- src/headless/config/ConfigContext.tsx
- src/headless/config/useConfigHelper.tsx
draft for managing local state via a headless hook.
- adds getters and setters for selected fields and selected field mappings
- does not include orchestration or auto filling of fields pulled from hydrated Revision 
note this work is not exported yet and sits in the headless folder under development
handling initializing and validating proper config
> feat: headless useConfig

- src/components/auth/Oauth/AuthorizationCode/NoWorkspaceEntry/NoWorkspaceOauthFlow.tsx
- src/components/auth/Oauth/AuthorizationCode/OAuthWindow/OAuthWindow.tsx
- src/components/auth/Oauth/AuthorizationCode/WorkspaceEntry/WorkspaceOauthFlow.tsx
- src/components/auth/Oauth/AuthorizationCode/useOAuthPopupURL.ts
part 2 followup to https://ampersand-company.slack.com/archives/C082KPRN4R4/p1746117090872019
problem: url can be cached by react-query which will auto popup the window even when not ready
solution: add a separate state to track whether url is active
- adds additional checks for error and oauth url
- fixes async call to refetch oauth url (will await for response, instead of autofire)
> fix: oauth cached url

- src/components/auth/Oauth/AuthorizationCode/OAuthWindow/OAuthWindow.tsx
- src/components/auth/Oauth/AuthorizationCode/OAuthWindow/windowHelpers.tsx
problem: https://ampersand-company.slack.com/archives/C082KPRN4R4/p1746215768712599?thread_ts=1746117090.872019&cid=C082KPRN4R4
When the window is closed (likely from backend trigger), the auth error is triggered automatically via the window closed logic. It seems the success event may not be captured before the window is closed causing the error:
```onError?.("Authentication was cancelled. Please try again.");```
When the window closes we add in an extra cache invalidation to force the connection to refresh (which should trigger a re-routing to the configure component)
We also pre-emptively add a manual cache override if a success event is received. 
Hubspot and Salesforce work as expected in mail-monkey.
> fix: have connections query invalidate on window close

- .github/dependabot.yml
See https://github.com/amp-labs/react/pull/1052, updating this dependency causes Node engine requirements to get bumped, which breaks the build & prevents us from publishing to npm.
> build: disable dependabot for openapi-generator-cli

- src/components/auth/Oauth/AuthorizationCode/NoWorkspaceEntry/NoWorkspaceEntryContent.tsx
- src/components/auth/Oauth/AuthorizationCode/NoWorkspaceEntry/NoWorkspaceOauthFlow.tsx
From the reported bug, it seems the connection is failing to connect from 
1 ) success event is not being captured by the client when the backend closes the window (difficult to duplicate)
2) when the window closes, the connection list is not being refetched 
This PR adds more refetching redundancy to No Workspace Auth flow, adds a loading/refetching state, asks for a refetch before submitting the oauth url. 
- add loading message when fetching connections
- hide error message when fetching connections
- disable button when fetching connections
- add refetching connections on window close and on success connect
note: this solution has not been applied to workspace workflows as the amount of overfetching can be a bit much without confirming this works as a solution.
> fix: reloading connection

- src/headless/config/useConfigHelper.tsx
Currently lots of context is needed to submit a config correctly namely several fields destination, schedule, objectName, and selectedFields are required. The first 3 fields should be able to be inserted via the backend in the future, selectedFields is required by the builder may not know they must add required fields to the selected fields by default. This useConfig helper will prefill required fields. 
- prefill destination, schedule, objectName and required fields into Selected fields 
- upon setting selectedFields 
- upson setting selectedFieldMappings
- rename key to objectName for easier maintanence
note code is still in separate folder that is being tested via an export branch.
> feat: config prefill default values from manifest

- tsconfig.json
- vite.config.ts
adds source maps so chrome can see code rather than transpiled letters.
> build: add source maps for debugging

- src/headless/config/useConfigHelper.tsx
This PR adds support for updating the write features in the config. 
- support enable /disable write per objectName
- support value defaults
- support field settings
use `_default` for value defaults in field settings
code is in headless folder non public, to be tested in sample app
> feat: support headless advanced write 

- src/components/auth/Oauth/AuthorizationCode/OAuthWindow/OAuthWindow.tsx
removes check for oauthWindow. 
we aren't guaranteed access to the window since the window will be coming from a different origin (hubspot). 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Cross-Origin-Opener-Policy
- we should consider redirecting to the clients website
> fix: remove oauthwindow actions to close window

- src/components/auth/Oauth/AuthorizationCode/NoWorkspaceOauthFlow2/NoWorkspaceOauthFlow2.tsx
- src/components/auth/Oauth/OauthFlow/OauthFlow.tsx
- src/hooks/mutation/useCreateOauthConnectionMutation.ts
attempts to build the oauth logic from scratch in attempt to debug oauth flow
- Uses own window logic. Creates one window listener on the parent app and only removes when unmounted (no fancy intervals)
- Switches from cached url fetching to async url trigger -> less use states to track. No additional callbacks to track.
- self-contained only to NoWorkspaceOauth flow; will move forward with Workspace fix correct.
- less error handling logic
- refetches connections before submitting for new url
If this code doesn't pass in production, the likely issue is that we need to follow the standard where the client origin is passed in the callback for message broadcast. Currently now set to '*' in the backend; the message should be broadcasted to any receiver in the browser.
> refactor: noWorkspaceOauthFlow2

- src/headless/installation/useCreateInstallation.ts
- src/headless/installation/useDeleteInstallation.ts
- src/headless/installation/useInstallation.ts
- src/headless/installation/useUpdateInstallation.ts
adds callbacks so that the builder has access to the success, error, and settled state given by tanstack-query. 
headless folder is not exposed yet.
> feat: add callbacks and docs to CRUD installation hook

- src/components/Configure/state/HydratedRevisionContext.tsx
problem: when the user tries to connect via InstallProvider, the component may error out because the token needs to be refreshed. The ability to update the authentication does not show up since the revision is not available.
solution: the hydrated revision error screen adds the ability to re-authenticate as well as delete connection.
> [ENG-2258] feat: add update auth flow to hydrated revision

- src/headless/config/useConfigHelper.tsx
- src/headless/installation/useCreateInstallation.ts
- src/headless/installation/useDeleteInstallation.ts
- src/headless/installation/useUpdateInstallation.ts
adds ability for config hook to sync with server state
- adds cache invalidation for CRUD installations so that queries will re-fetch upon mutations
- adds useEffect to track when to sync config state with server state (when new installation is available)
- adds side effect support for CRUD installation options.
still hidden behind export folder. note to rebase on main instead of headless-export
test here: https://github.com/amp-labs/headless-sample-app/pull/1
> [ENG-2291] feat: add syncInstallationConfig to useConfigHelper

- src/headless/config/useConfigHelper.tsx
customer feedback said sync was a little confusing. renames sync to reset. 
- existing reset call is unused in demos. (we don't support passing in initial config yet)
- switched implementation to only use reset
> [2313] refactor: rename sync to reset

- src/headless/config/ConfigContext.tsx
- src/headless/config/types.ts
- src/headless/config/useConfigHelper.tsx
- src/headless/index.ts
- src/headless/installation/useCreateInstallation.ts
- src/headless/installation/useUpdateInstallation.ts
- src/public/index.ts
ConfigContent and UpdateInstallationContent types are being managed by the openAPI spec which causes confusion to the builder. This PR 
- adds a bridge type to merge the types and simplify the types needed by the builder. 
- remove generated types so that we selectively expose types as needed
> type: add config bridge types

- package.json
- yarn.lock
Reverts amp-labs/react#1116
build error is happening from this plugin, reverting to unblock release.
> Revert "build(deps-dev): bump rollup-plugin-visualizer from 5.12.0 to 6.0.0"

- generated-sources/api/src/models/FieldSetting.ts
- package.json
- scripts/fix-default-field-setting.ts
- yarn.lock
`default` is being changed to `_default` by the auto-gen openapi-cli, which does not match with reference docs. 
- adds a script to fix the default field setting type
- fixes the default field setting type in the generated API
- `yarn generate-api` will now run the post process script after gen. 
This solution is a bit fragile, if the FieldSettings type is renamed; this post process script will not run correctly. 
other solutions attempted: 
- modifying moustache template (maintenance + learning curve) - we're likely switching gen tools so did not pursue
- grep / sed - replaces all _default -> may be unsafe
`yarn generate-api`
> [ENG-2336] fix: default field setting type

- src/components/Configure/InstallIntegration.tsx
- src/components/Configure/content/manage/ManageContent.tsx
- src/components/Connect/RemoveConnectionSection.tsx
- src/context/InstallIIntegrationContextProvider/InstallIntegrationContextProvider.tsx
adds remove connection section to manage content; previously could not uninstall if no installation. 
- add reset to provider context
- style: remove connection section
> [ENG-2990] feat: add remove connection section to manage content

- src/components/Configure/content/fields/WriteFields/WriteFieldsV2.tsx
refactors the write fields to use the new CheckboxPagination component. See part 1: https://github.com/amp-labs/react/pull/1157/files
> [ENG-380] feat: add pagination to write fields

- src/components/Configure/InstallIntegration.tsx
- src/components/Configure/content/fields/ObjectMapping.tsx
- src/components/Configure/content/fields/RequiredFields.tsx
- src/components/Configure/content/useSelectedConfigureState.tsx
- src/components/Configure/nav/ObjectManagementNav/v2/index.tsx
- src/components/Connect/ConnectedSuccessBox.tsx
- src/components/auth/Oauth/AuthorizationCode/NoWorkspaceOauthFlow2/NoWorkspaceOauthFlow2.tsx
- src/components/auth/Oauth/AuthorizationCode/OauthFlow2/OauthFlow2.tsx
- src/components/auth/Oauth/AuthorizationCode/useOAuthPopupURL.ts
- src/context/ConnectionsContextProvider.tsx
- src/context/ProjectContextProvider.tsx
- src/hooks/query/index.ts
- src/hooks/query/useProjectQuery.ts
- src/hooks/query/useProjectWithEntitlementsQuery.ts
Part 2 - We need to refactor the projectProvider since AmpersandProvider will no longer be able to make an API call without a groupRef/consumerRef. 
Previously we had calls for projectId go to useAmpersandProviderProps(). For instances needing appName, project (object), and other react query data, we make calls to useProjectQuery.
- replace useProject with useProjectQuery
refactor in progress for ProjectProvider
part 1: https://github.com/amp-labs/react/pull/1224
~~1. add props provider to AmpersandProvider~~
~~2. refactor basic uses of projectId~~
**3. refactor uses of Project, isProjectLoading, appName (to use projectListQuery)**
4. remove ProjectProvider from AmpersandProvider
5. do steps 1 - 4 with IntegrationList provider 
No visual changes in app expected for InstallIntegration, …
> [ENG-2419] refactor: useProjectQuery hook

- src/context/AmpersandContextProvider/AmpersandContextProvider.tsx
- src/context/JwtTokenContextProvider.tsx
- src/services/api.ts
changes getToken types to be less likely to mix up.
- getToken: ({consumerRef, groupRef}) => Promise<string>
> build: update types to be an object

- src/components/Configure/InstallIntegration.tsx
adding installation provider gives access to groupRef and consumerRef to the apiService in InstallIntegration -- needed for JWT support.
- adds InstallationProvider to InstallIntegration
- JWT support is still disabled in InstallIntegration
1. ~~support JWT through InstallationProvider~~
2. **add InstallationProvider to InstallIntegration**
3. refactor legacy setAndCreate calls to use react-query / centralized api service
4. test InstallIntegration Create and Update flow using JWT
5. remove error dialog for InstallIntegration JWT support
> [ENG-2417] build: add installation provider to install integration

- src/components/Configure/content/fields/OptionalFields/OptionalFieldsV2.tsx
- src/components/Configure/content/fields/WriteFields/WriteFieldsV2.tsx
- src/components/ui-base/Checkbox/CheckboxPagination.tsx
- src/components/ui-base/Checkbox/checkboxPagination.module.css
checkbox components are paginated, but with hundreds of fields a searching ux is need. This PR adds the search functionality to the paginated checkbox component and refactors optional fields and write to use the new search ux.
- pagination moved down since less likely to be used with search
- filter applies to groups of fields 
- note the buttons moving to the bottom still makes the ux clucky to navigate to next page since the page length changes. should be less of a concern with search being instructed by builders to find specific fields.
> [ENG-2476] feat: checkbox search

- package.json
- yarn.lock
- revert to earlier version of vite 
- fixes the build issue with vite 7
note: my hubspot and saleforce credentials are broken; need to fix.
> build: revert to vite 5

- src/components/Configure/content/fields/ValueMapping/ValueMappingItem.tsx
- src/components/Configure/content/fields/ValueMapping/ValuesMapping.tsx
customer reported fix: 
problem: 
1. value mappings doesn't clear disabled when swapping values
2. modifying value mappings save button remains disabled 
solution: 
- change the selection to only allow values not yet selected 
- check the value mappings object and update isModified accordingly
does not require all selections of value mappings to be mapped before submit/update
> [ENG-2581] fix/ux: allow only unique selections in value mappings

- src/components/Configure/content/ConfigureInstallationBase.tsx
- src/components/Configure/content/fields/ValueMapping/ValueMappingItem.tsx
- src/components/Configure/content/fields/ValueMapping/ValuesMapping.tsx
- src/components/Configure/content/fields/ValueMapping/setValueMapping.ts
- src/components/Configure/content/fields/ValueMapping/utils.ts
- src/components/Configure/nav/ObjectManagementNav/v2/Tabs/index.tsx
- src/components/Configure/state/ConfigurationStateProvider.tsx
- src/components/Configure/state/utils.ts
- src/components/Configure/types.ts
Tracking the `isModified` state has resulted in unnecessary complexity as the product has scaled. With multiple states updating a legacy draft state and a legacy saved state, the “source of truth” has been ambiguous, leading to bugs that are difficult to debug. A state rewrite was needed to debug this issue. 
This PR simplifies the `ValueMappings` implementation in the following ways:  
- **Remove inline validation**: Since we now enforce uniqueness at the selection step (via filter), post-input validation is no longer required. This reduces maintenance burden.  
- **Remove `isValueMappingsModified` state tracking**: No longer stored in state; simplifies logic and reduces potential divergence.  
- **Add `isValueMappingsEqual` helper**: Ensures `undefined` (server) and `{}` (local) are …
> fix/rm/feat: simplify value mapping

- src/components/Configure/content/ConfigureInstallationBase.tsx
- src/components/Configure/content/CreateInstallation.tsx
- src/components/Configure/content/UpdateInstallation.tsx
- src/components/Configure/content/fields/FieldDefaultValueMapping/setValueDefaultWriteField.tsx
- src/components/Configure/content/fields/WriteFields/setNonConfigurableWriteField.tsx
- src/components/Configure/content/useMutateInstallation.tsx
- src/components/Configure/nav/ObjectManagementNav/v2/Tabs/index.tsx
- src/components/Configure/state/ConfigurationStateProvider.tsx
- src/components/Configure/state/utils.ts
- src/components/Configure/types.ts
- src/headless/installation/useUpdateInstallation.ts
Continued work to migrate write modified state to derived state to reduce state management complexity.
- fix: headless write objects update mask
- add write objects to update mask if it is modified from server state
> [ENG-2596] refactor: remove write modified state
